const { C, S, ul, tb } = require('./_h');

module.exports = {
  id: 'card', nome: 'Cardiologia', ic: '🫀',
  desc: 'IC, arritmias, valvopatias e anticoagulação, endocardite, amiloidose e cardiomiopatias restritivas, oclusão arterial aguda.',
  subs: [
    S('card-ic', 'Insuficiência cardíaca', [
      C('quadrupla', 2022, 'IC com FE reduzida: qual a terapia quádrupla?',
        '<b>Betabloqueador + IECA/INRA (sacubitril-valsartana) + espironolactona + iSGLT2.</b>'),
      C('extras', 2022, 'IC FEr: quando acrescentar hidralazina + nitrato, vericiguat e ivabradina?',
        ul('<b>Hidralazina + nitrato</b>: negros sintomáticos', '<b>Vericiguat</b>: sintomáticos com IC em piora', '<b>Ivabradina</b>: FE &lt; 35%, ritmo sinusal com <b>FC &gt; 70 bpm</b>')),
      C('dispositivos', 2022, 'IC FEr sintomática com FE &lt; 35%: quando indicar ressincronizador e CDI?',
        '<b>Ressincronizador</b>: ritmo sinusal com <b>BRE &gt; 130 ms</b> ou não-BRE &gt; 150 ms. <b>CDI</b>: principalmente etiologia isquêmica.'),
      C('furo-dig', 2022, 'Furosemida e digoxina reduzem mortalidade na IC?',
        '<b>Não.</b> Melhoram sintomas e reduzem hospitalização.'),
      C('hidralazina', 2025, 'Qual cuidado ao usar hidralazina em coronariopata?',
        'Pode <b>agravar ou desencadear angina</b> em quem tem histórico ou substrato coronariano.'),
    ]),

    S('card-arr', 'Arritmias: fibrilação atrial e Brugada', [
      C('fa-obj', 2025, 'Quais os dois objetivos no manejo da fibrilação atrial?',
        '<b>Controle de sintomas</b> (controle de frequência ou de ritmo) e <b>prevenção de tromboembolismo</b> (anticoagulação).'),
      C('fa-estrat', 2025, 'FA: qual a estratégia inicial e o que deve ser tentado?',
        'A maioria começa com <b>controle de frequência</b>, mas pelo menos <b>uma tentativa de controle de ritmo</b> deve ser feita.'),
      C('fa-cv', 2025, 'FA &gt; 48 h ou de duração indefinida: como anticoagular na cardioversão?',
        '<b>Antes</b> (pelo menos <b>3 semanas</b> de anticoagulação efetiva) e <b>depois</b> da cardioversão.'),
      C('fa-ablacao', 2025, 'Controle de ritmo na FA: fármaco ou ablação?',
        'Os estudos favorecem a <b>ablação</b> na maioria dos casos (seguimento de 2 anos). Se fármaco, sem doença estrutural: <b>propafenona</b> é uma das principais escolhas.'),
      C('brugada-def', 2022, 'Síndrome de Brugada × padrão de Brugada: qual a diferença?',
        '<b>Síndrome</b>: ECG típico + clínica sugestiva de arritmia ventricular com risco de vida. <b>Padrão</b>: o mesmo ECG em pessoa <b>assintomática</b>.'),
      C('brugada-ecg', 2022, 'Qual o ECG típico da síndrome de Brugada?',
        '<b>Pseudobloqueio de ramo direito</b> com <b>supradesnivelamento persistente do ST em V1–V2</b>.'),
    ]),

    S('card-valv', 'Valvopatias e anticoagulação', [
      C('em-anticoag', 2022, 'Estenose mitral reumática: quando anticoagular e com qual droga?',
        'EM moderada a grave com <b>FA</b> (paroxística, persistente ou permanente), <b>embolia prévia</b> ou <b>trombo atrial esquerdo</b> → <b>varfarina</b> (antagonista da vitamina K).'),
      C('doac-ci', 2022, 'Quando os anticoagulantes orais diretos estão contraindicados?',
        '<b>Síndrome antifosfolípide</b>, <b>trombo intracardíaco</b> e <b>prótese valvar mecânica</b> (falta de eficácia ou de estudos). São aprovados para FA <b>não valvar</b>.',
        '<b>Macete:</b> SAF, trombo e prótese mecânica → varfarina.'),
      C('bicuspide', 2025, 'Valva aórtica bicúspide: qual a associação e quais aortopatias?',
        'Associação com <b>aortopatia em até 70%</b>: ectasia, aneurisma e <b>dissecção da aorta ascendente</b>.'),
      C('im-ausc', 2025, 'Insuficiência mitral crônica grave: como é a ausculta?',
        'Sopro <b>holossistólico</b> no foco mitral irradiando para a <b>axila</b>, melhor em decúbito lateral esquerdo. <b>B1 hipofonética</b>; <b>B3</b> se o VE dilatar.'),
      C('im-conduta', 2025, 'Insuficiência mitral: qual exame confirma e qual o tratamento cirúrgico de escolha?',
        '<b>Ecocardiograma transtorácico</b> confirma e gradua. Cirurgia de escolha: <b>plástica mitral</b>, se etiologia e anatomia favoráveis (sobretudo no <b>prolapso</b>).'),
    ]),

    S('card-ei', 'Endocardite infecciosa: cirurgia', [
      C('cirurgia', 2022, 'Endocardite de valva nativa esquerda: quando indicar cirurgia precoce?',
        ul('<b>IC refratária</b> por disfunção valvar (insuficiência mitral ou aórtica)', 'Infecção <b>complicada</b>: abscesso anular/aórtico, fístula, bloqueio cardíaco; germes multirresistentes e <b>fungos</b>; choque séptico', 'Infecção <b>persistente</b>: bacteremia ou febre &gt; 7 dias com antibiótico adequado', '<b>Embolização frequente</b> apesar do antibiótico', 'Endocardite <b>precoce em prótese</b>')),
      C('adiar', 2022, 'Endocardite com AVC isquêmico maior ou hemorragia intracraniana: quando operar?',
        'Adiar a cirurgia por <b>≥ 4 semanas</b>: a circulação extracorpórea reduz a perfusão cerebral e exige anticoagulação.'),
    ]),

    S('card-amil', 'Amiloidose e cardiomiopatias restritivas', [
      C('tipos', 2024, 'Quais os principais tipos de amiloidose sistêmica?',
        '<b>AL</b> (cadeia leve, primária), <b>AA</b> (secundária/reativa), <b>ATTR</b> hereditária (mutação autossômica dominante) ou senil/wild-type, e a de <b>β2-microglobulina</b> na doença renal terminal.'),
      C('aa', 2024, 'Amiloidose AA: o que é e quais as causas?',
        'Depósito da proteína amiloide A sérica (reagente de fase aguda) por <b>inflamação prolongada</b>: AR, artrite juvenil, espondilite anquilosante, DII, infecções crônicas, <b>febre familiar do Mediterrâneo</b>, neoplasias, Castleman. Frequente em países em desenvolvimento; a AL predomina nos desenvolvidos.'),
      C('aa-rim', 2024, 'Como a amiloidose acomete o rim?',
        'Proteinúria assintomática, <b>síndrome nefrótica</b>, declínio progressivo ou DRC terminal. Se o depósito é só vascular ou tubular: insuficiência renal com pouca ou nenhuma proteinúria.'),
      C('ecg-eco', 2026, 'Amiloidose cardíaca: qual a "dissociação" entre ECG e eco?',
        '<b>Baixa voltagem no ECG</b> com <b>paredes espessadas no eco</b> (o infiltrado extracelular "dilui" o sinal elétrico). Sempre suspeitar de doença infiltrativa.'),
      C('eco', 2026, 'Quais os achados de eco e strain na amiloidose cardíaca?',
        'Paredes <b>hiper-refringentes</b> (brilho granular), espessamento valvar, átrios aumentados, disfunção diastólica até padrão restritivo. Strain: <b>preservação do ápice (apical sparing)</b>, com redução nos segmentos basais e médios.',
        '<b>Macete:</b> hiper-refringência + baixa voltagem + apical sparing = amiloidose.'),
      C('rm', 2026, 'Qual o achado da RM cardíaca na amiloidose?',
        '<b>Realce tardio difuso subendocárdico</b>, T1 nativo elevado, volume extracelular muito aumentado e dificuldade em achar o ponto de nulagem miocárdica.'),
      C('dd', 2026, 'Amiloidose × hemocromatose × isquemia × cardiomiopatia dilatada: como diferenciar?',
        '<b>Hemocromatose</b>: sobrecarga de ferro, sem apical sparing, RM com <b>T2* reduzido</b>. <b>Isquemia</b>: segmentar, sem hiper-refringência ou baixa voltagem difusa. <b>Degeneração idiopática</b>: paredes finas e remodelamento excêntrico.'),
      C('attr-al', [2024, 2026], 'Amiloidose ATTR × AL: epidemiologia?',
        '<b>ATTR wild-type</b>: muito frequente em idosos (&gt; 60 anos). <b>AL</b>: qualquer idade adulta, associada a discrasias plasmocitárias/mieloma.'),
      C('dx', 2024, 'Amiloidose cardíaca: o que sugere cada exame?',
        '<b>Cintilografia com pirofosfato</b> com alta captação → <b>ATTR</b>. <b>Relação kappa/lambda</b> alterada (cadeias leves) → <b>AL</b>. Biópsia endomiocárdica confirma. Teste genético para ATTR hereditária.'),
      C('al-clin', 2024, 'Hipertrofia concêntrica + macroglossia + equimoses periorbitárias: qual exame é mais específico?',
        'Achados clássicos de amiloidose <b>AL</b> → <b>relação kappa/lambda</b>.'),
      C('tto', 2024, 'Qual o tratamento da amiloidose AL e da ATTR?',
        '<b>AL</b>: quimioterapia para reduzir as cadeias leves. <b>ATTR</b>: estabilizador da transtirretina (<b>tafamidis</b>) ou transplante hepático nas formas hereditárias.'),
      C('eos-fases', 2026, 'Cardiopatia eosinofílica: quais as 3 fases?',
        ul('<b>Necrosante</b>: eosinófilos liberam proteína básica maior → necrose, ainda sem alteração no eco', '<b>Trombótica</b>: trombos murais no ápice → obliteração apical', '<b>Fibrótica</b>: <b>endomiocardiofibrose</b>, retração do aparelho subvalvar → insuficiências valvares; fenótipo <b>restritivo</b>')),
      C('eos-eco', 2026, 'Hipereosinofilia + eco com obliteração apical, trombos aderidos, valvopatia por tração, FE preservada e átrios grandes: qual diagnóstico?',
        'Cardiomiopatia <b>restritiva por endomiocardiofibrose</b> (fase fibrótica da cardiopatia eosinofílica), com congestão predominante de VD.'),
    ]),

    S('card-oaa', 'Oclusão arterial aguda', [
      C('emb-trom', 2026, 'Oclusão arterial aguda embólica × trombótica: como diferenciar?',
        tb(['', 'Embólica', 'Trombótica'], ['Início', 'Súbito', 'Agudo/subagudo'], ['Dor', 'Aguda e intensa', 'Moderada/intensa'], ['Cardiopatia', 'Frequente', 'Pode ou não ter'], ['Claudicação prévia', 'Não', 'Frequente'], ['Pulsos contralaterais', '<b>Presentes</b>', '<b>Ausentes</b>'], ['Fonte emboligênica', 'Presente', 'Ausente'], ['Arteriografia', '<b>Taça invertida</b>, aterosclerose mínima', '<b>Ponta de lápis</b>, aterosclerose difusa'])),
      C('pulso', 2026, 'Por que pesquisar dissociação pulso-precórdio na oclusão arterial aguda?',
        'A dissociação pulso-precórdio (anisocardiosfigmia) é achado de <b>arritmia</b> (ex.: FA), fonte de embolia.'),
    ]),
  ],
};
