const { C, S, ul, tb, svgFluxo } = require('./_h');

module.exports = {
  id: 'endo', nome: 'Endocrinologia', ic: '🧪',
  desc: 'Diabetes, tireoide, adrenal, Cushing, NEM e poliglandulares, hipercalcemia, osso e obesidade.',
  subs: [
    S('endo-dm', 'Diabetes: DM2, DM1 e diabetes gestacional', [
      C('dm2-3q', 2022, 'DM2: quais as 3 perguntas para escolher a terapia?',
        ul('<b>Risco cardiovascular?</b> Baixo/intermediário ou alto/muito alto', '<b>Obesidade?</b> Se sim, preferir <b>GLP-1 ou tirzepatida</b>', '<b>HbA1c &gt; 7,5%?</b> Iniciar <b>terapia combinada</b>')),
      C('totg', 2026, 'TOTG 75 g na gestante: quais os valores normais?',
        'Todos abaixo de <b>92 / 180 / 153 mg/dL</b> (jejum / 1 h / 2 h).',
        '<b>Armadilha:</b> na gestante não existe "pré-diabetes": é DMG ou normal.'),
      C('dm1-dx', 2026, 'DM1: qual o mecanismo e como se confirma?',
        '<b>Autoimunidade contra células β</b>. Confirmação: <b>peptídeo C baixo</b> + autoanticorpos (<b>anti-GAD, IA-2, ZnT-8</b>).'),
      C('dm1-tto', 2026, 'Quais os pilares do tratamento do DM1?',
        'Educação, <b>contagem de carboidratos</b>, ajuste ao exercício e esquema <b>basal-bolus</b> com análogos rápidos e basais prolongados.'),
      C('dm1-bomba', 2026, 'DM1: quando indicar sistema de infusão contínua de insulina?',
        'Controle não atingido apesar de múltiplas aplicações otimizadas, especialmente com <b>hipoglicemias graves</b> e/ou metas não alcançadas. Melhora a variabilidade e reduz hipoglicemias.'),
    ]),

    S('endo-tir', 'Tireoide: tireotoxicose e nódulo tireoidiano', [
      C('raiu-baixo', 2022, 'Quais as causas de tireotoxicose com captação de iodo (RAIU) baixa?', '<b>Tireotoxicose factícia</b> e <b>tireoidite</b>.'),
      C('facticia', 2022, 'Tireotoxicose factícia: o que ela não faz?',
        'Não faz <b>oftalmopatia</b> e não faz <b>bócio</b>. Pode aparecer como <b>T3-toxicose</b> (quando o hormônio ingerido é T3).'),
      C('t3-t4', 2025, 'T3 alto com T4L normal × T4L alto com T3 normal: o que cada padrão sugere?',
        '<b>T3 alto + T4L normal</b>: aumento da função glandular (<b>Graves, bócio nodular e multinodular</b>). <b>T4L alto + T3 normal</b>: <b>tireoidites</b> (a glândula destruída libera T4 pré-formado de uma vez).',
        '<b>Macete:</b> glândula trabalhando mais → T3; glândula sendo destruída → T4.'),
      C('cintilo', 2025, 'O que mostra a cintilografia em cada causa de hipertireoidismo?',
        tb(['Doença', 'Cintilografia'], ['Graves', 'Captação difusa (pode mostrar lobo piramidal)'], ['Bócio multinodular tóxico', 'Áreas quentes e frias; múltiplas áreas captantes'], ['Nódulo autônomo', 'Nódulo quente com <b>supressão do restante</b> da glândula'], ['Tireoidite', 'Captação muito baixa (RAIU &lt; 5%)'])),
      C('bmnt', 2025, 'Bócio multinodular tóxico: achado e tratamento definitivo?',
        'Hipertireoidismo + captação em <b>múltiplas áreas</b> com hipocaptação no restante. Tratamento definitivo: <b>radioiodo</b>; cirurgia em bócios volumosos ou compressivos.'),
      C('nod-tsh', 2026, 'Nódulo tireoidiano: qual o primeiro exame e o que fazer com o resultado?',
        '<b>TSH.</b> Suprimido → <b>cintilografia</b>. Normal ou elevado → <b>ultrassom com TIRADS</b> para decidir seguimento ou PAAF.'),
      C('tirads-risco', 2026, 'Quais achados ultrassonográficos de maior risco pesam no TIRADS?',
        'Hipoecogenicidade acentuada, <b>microcalcificações</b>, margens irregulares e nódulo <b>mais alto do que largo</b>.'),
      C('tirads-paaf', 2026, 'TIRADS: a partir de qual tamanho indicar PAAF?',
        tb(['Categoria', 'PAAF se'], ['TIRADS 3', '≥ 2,5 cm'], ['TIRADS 4', '≥ 1,5 cm'], ['TIRADS 5', '≥ 1 cm']) + 'Abaixo disso: seguimento conforme a categoria e o crescimento.',
        '<b>Macete:</b> 2,5 → 1,5 → 1 cm conforme o risco sobe.'),
    ]),

    S('endo-adr', 'Adrenal: incidentaloma e carcinoma adrenocortical', [
      C('inc-cortisol', 2022, 'Incidentaloma adrenal: como investigar hipercortisolismo e em quem?',
        'Teste de supressão com <b>1 mg de dexametasona</b> — em <b>todos</b> os incidentalomas.'),
      C('inc-aldo', 2022, 'Incidentaloma adrenal: como investigar hiperaldosteronismo e em quem?',
        'Relação <b>aldosterona/renina</b>. Na anotação de 2022: apenas em quem tem <b>hipertensão ou hipocalemia</b>.'),
      C('inc-feo', 2022, 'Incidentaloma adrenal: como investigar feocromocitoma e em quem?',
        '<b>Metanefrinas</b> urinárias ou plasmáticas. Na anotação de 2022: nas lesões com densidade <b>&gt; 10 UH</b>.'),
      C('inc-diverg', [2022, 2026], 'Suas anotações divergem sobre quem rastrear no incidentaloma. O que cada uma diz?',
        '<b>2022</b>: cortisol em todos; aldosterona só com HAS ou hipocalemia; metanefrinas só se &gt; 10 UH. <b>2026</b>: excluir feocromocitoma, Cushing subclínico e hiperaldosteronismo em <b>todo</b> incidentaloma. Na dúvida, siga o gabarito da questão.'),
      C('massa-susp', 2026, 'Quais achados de imagem sugerem carcinoma adrenocortical?',
        'Massa <b>≥ 4 cm</b> + densidade <b>&gt; 20 UH</b> + <b>heterogeneidade</b>.'),
      C('massa-conduta', 2026, 'Massa adrenal suspeita (&gt; 4 cm e &gt; 20 UH): qual a conduta?',
        '<b>Adrenalectomia</b> (aberta ou laparoscópica, conforme a segurança cirúrgica).'),
      C('dheas', 2023, 'Virilização com DHEAS elevado: qual a origem provável?',
        'Origem <b>adrenal</b> — pensar em <b>carcinoma de adrenal</b>. A síndrome dos ovários policísticos causa hiperandrogenismo mais leve.'),
      C('func', 2023, 'Tumores adrenocorticais funcionantes podem secretar o quê?',
        'Cortisol e precursores, andrógenos adrenais e precursores e, raramente, estrógenos ou mineralocorticoides.'),
      C('cortisol-basal', 2023, 'Cortisol basal elevado confirma hipercortisolismo?',
        'Não. Mas <b>afasta a deficiência</b> de cortisol.'),
    ]),

    S('endo-cush', 'Síndrome de Cushing', [
      C('passo1', 2022, 'Síndrome de Cushing, passo 1: como confirmar o hipercortisolismo?',
        'Pelo menos <b>2 de 3</b> testes: ' + ul('Supressão com <b>1 mg de dexametasona</b>', '<b>Cortisol urinário de 24 h</b>', '<b>Cortisol salivar noturno</b>') + 'Confirmação laboratorial <b>antes</b> de qualquer imagem, e sempre descartar corticoide exógeno.'),
      C('passo2', 2022, 'Síndrome de Cushing, passo 2: o que o ACTH define?',
        svgFluxo('Investigação da síndrome de Cushing pelo ACTH',
          [{ x: 95, y: 6, w: 150, h: 40, t: ['Hipercortisolismo', 'confirmado'], cor: 'azul' },
           { x: 8, y: 76, w: 150, h: 40, t: ['ACTH suprimido:', 'origem adrenal'], cor: 'ouro' },
           { x: 182, y: 76, w: 150, h: 40, t: ['ACTH normal ou alto:', 'central ou ectópico'], cor: 'verde' },
           { x: 8, y: 138, w: 150, h: 40, t: ['imagem', 'das adrenais'], cor: 'claro' },
           { x: 182, y: 138, w: 150, h: 52, t: ['supressão 8 mg ou', 'desmopressina', '+ RM de hipófise'], cor: 'claro' }],
          [[140, 46, 90, 74], [200, 46, 250, 74], [83, 116, 83, 136], [257, 116, 257, 136]])),
      C('hddst', 2023, 'Cushing ACTH-dependente: o que esperar na doença de Cushing × ACTH ectópico?',
        tb(['Teste', 'Doença de Cushing (hipófise)', 'ACTH ectópico'], ['Dexametasona dose alta (Liddle 2)', '<b>Suprime</b> o cortisol', 'Não suprime'], ['Estímulo com CRH', '<b>Estimula</b> o ACTH', 'Não estimula'])),
      C('img', 2023, 'Após o teste dinâmico, qual imagem pedir em cada caso?',
        'Doença de Cushing → <b>RM de sela túrcica</b> (adenoma e plano cirúrgico). Ectópico → procurar o tumor, principalmente no <b>pulmão</b> (carcinoma de pequenas células, <b>oat cell</b>).'),
    ]),

    S('endo-nem', 'NEM e síndromes poliglandulares autoimunes', [
      C('nem1', 2025, 'NEM tipo 1: quais glândulas, qual a manifestação mais frequente e qual o gene?',
        '<b>Paratireoide, pâncreas e pituitária</b>. Manifestação mais frequente: <b>hiperparatireoidismo</b>. Gene <b>MEN1</b>.',
        '<b>Macete:</b> NEM 1 = PPP (paratireoide, pâncreas, pituitária).'),
      C('nem2', 2025, 'NEM tipo 2: gene e componentes do 2A e do 2B?',
        'Proto-oncogene <b>RET</b>. <b>2A</b>: carcinoma medular de tireoide + feocromocitoma + <b>hiperparatireoidismo</b>. <b>2B</b>: carcinoma medular + feocromocitoma + <b>neuromas mucosos</b> + <b>fenótipo marfanoide</b>.'),
      C('nem2-cmt', 2025, 'Em qual NEM o carcinoma medular de tireoide é mais agressivo?', '<b>NEM 2B.</b>'),
      C('nem4', 2025, 'O que é a NEM tipo 4?', 'Rara, parecida com a NEM 1, causada por mutação no gene <b>CDKN1B</b>.'),
      C('spga', [2023, 2025], 'Síndrome poliglandular autoimune tipo 1 × tipo 2:',
        tb(['', 'Tipo 1', 'Tipo 2'], ['Genética', 'Autossômica recessiva, gene <b>AIRE</b>', 'Poligênica, HLA-DQ2/DR4'], ['Tríade', '<b>Candidíase mucocutânea</b> crônica, <b>hipoparatireoidismo</b>, <b>Addison</b>', '<b>Addison</b>, <b>tireoidite autoimune</b> (Hashimoto/Graves), <b>DM1</b>'], ['Outros', 'Enamelopatia, enteropatias, falência gonadal precoce', 'Hipogonadismo primário e outras'], ['Diagnóstico', '≥ 2 componentes + anticorpo anti-interferon', '≥ 2 endocrinopatias autoimunes, excluída a tipo 1']),
        '<b>Macete:</b> tipo 1 = Candida + paratireoide + adrenal; tipo 2 = adrenal + tireoide + DM1.'),
    ]),

    S('endo-ca', 'Hipercalcemia', [
      C('fluxo', 2025, 'Hipercalcemia: qual o raciocínio diagnóstico a partir do PTH?',
        svgFluxo('Investigação da hipercalcemia',
          [{ x: 85, y: 4, w: 170, h: 36, t: ['Cálcio iônico alto'], cor: 'azul' },
           { x: 8, y: 68, w: 158, h: 44, t: ['PTH normal ou alto:', 'mediada por PTH'], cor: 'ouro' },
           { x: 174, y: 68, w: 158, h: 44, t: ['PTH baixo:', 'dosar PTHrP e vit. D'], cor: 'verde' },
           { x: 8, y: 132, w: 158, h: 56, t: ['hiperpara 1º e 3º,', 'hipercalcemia hipo-', 'calciúrica, lítio'], cor: 'claro', fs: 9 },
           { x: 174, y: 132, w: 158, h: 56, t: ['PTHrP: malignidade', '1,25-D: granuloma', '25-D: intoxicação'], cor: 'claro', fs: 9 }],
          [[140, 40, 90, 66], [200, 40, 250, 66], [87, 112, 87, 130], [253, 112, 253, 130]]) +
        'Cálcio iônico normal = pseudo-hipercalcemia. Outras causas não mediadas por PTH: mieloma múltiplo, insuficiência adrenal, excesso de vitamina A, imobilização, feocromocitoma, síndrome leite-álcali.'),
      C('salina', 2025, 'Hipercalcemia: efeito e efeito adverso da salina e da furosemida?',
        tb(['', 'Efeito', 'Adverso'], ['Salina', 'Corrige hipovolemia e aumenta calciúria; reduz Ca em <b>1–2 mg/dL</b>', 'Sobrecarga de volume'], ['Furosemida', 'Aumenta calciúria; reduz Ca em 0,5–1 mg/dL', '<b>Piora</b> a hipercalcemia se houver desidratação'])),
      C('calcitonina', 2025, 'Calcitonina na hipercalcemia: mecanismo, efeito e limitação?',
        'Inibe os osteoclastos; reduz Ca em 1–2 mg/dL. Efeito <b>transitório por taquifilaxia</b>.'),
      C('bisfos', 2025, 'Pamidronato × ácido zoledrônico na hipercalcemia:',
        'Os dois inibem e causam apoptose dos osteoclastos. Pamidronato normaliza o Ca em ~70%; <b>zoledrônico em ~90%</b>, com efeito de <b>~30 dias</b>. Adversos: hipocalcemia e <b>osteonecrose de mandíbula</b>; <b>contraindicado na insuficiência renal</b>.'),
      C('denos', 2025, 'Denosumabe na hipercalcemia: eficácia, lugar no tratamento e cuidados?',
        'Inibe atividade e diferenciação dos osteoclastos; normaliza o Ca em ≥ 70%. Indicado de <b>1ª linha pelo guideline mais recente de hipercalcemia da malignidade</b>. Adversos: hipocalcemia, fraturas atípicas e <b>rebote</b> se suspenso sem outra terapia.'),
      C('gc', 2025, 'Quando o glicocorticoide trata hipercalcemia?',
        'Nas <b>doenças granulomatosas</b> e <b>linfomas</b>, que aumentam a conversão de vitamina D: o corticoide inibe a 1-α-hidroxilase e reduz a 1,25-(OH)₂-vitamina D.'),
      C('maligna', 2026, 'Hipercalcemia maligna: qual o protocolo inicial considerado padrão-ouro na questão de 2026?',
        '<b>Hidratação vigorosa</b> (volume e calciurese) seguida de <b>bisfosfonato IV</b> para bloquear a reabsorção óssea.'),
    ]),

    S('endo-osso', 'Osteoporose e doença de Paget', [
      C('holiday-quando', 2026, 'Quando reavaliar o bisfosfonato no tratamento da osteoporose?',
        'Após <b>5 anos de bisfosfonato oral</b> ou <b>3 anos de ácido zoledrônico</b> IV.'),
      C('holiday-baixo', 2026, 'Osteoporose, baixo risco de fratura na reavaliação: qual a conduta?',
        'DMO estável e sem fraturas prévias → <b>drug holiday</b>, com reavaliação a cada 3–6 anos.'),
      C('holiday-alto', 2026, 'Osteoporose, alto risco de fratura na reavaliação: qual a conduta?',
        'Fratura osteoporótica antes/durante a terapia ou <b>T-score &lt; −2,5</b> → manter bisfosfonato oral por até <b>10 anos</b> e zoledrônico por até <b>6 anos</b>.'),
      C('paget-def', 2022, 'O que é a doença de Paget óssea?',
        'Desordem esquelética <b>focal</b> com remodelação óssea aumentada: reabsorção exacerbada e formação acelerada → osso desorganizado, menos resistente, com deformidades e fraturas. Doença óssea mais frequente depois da osteoporose; aumenta com a idade, pouco mais em homens.'),
      C('paget-lab', 2022, 'Paget: como a maioria se apresenta e como ficam cálcio e fósforo?',
        'Maioria <b>assintomática</b>, só com <b>fosfatase alcalina elevada</b> e achado radiográfico. <b>Cálcio e fósforo normais.</b> Maioria poliostótica. Locais: pelve, fêmur, coluna lombar, crânio.'),
      C('paget-rx', 2022, 'Paget: quais os achados radiográficos por fase?',
        ul('Inicial: osteólise localizada (lesão em "<b>chama de vela</b>")', 'Intermediária: espessamento cortical, expansão óssea, trabeculado grosseiro', 'Tardia: esclerose e aumento acentuado do osso') + 'Cintilografia: mais sensível e menos específica; mapeia a doença poliostótica.'),
      C('paget-tto', 2022, 'Qual o tratamento da doença de Paget?',
        'Bisfosfonato, de preferência <b>ácido zoledrônico</b>. Se contraindicado (ex.: DRC): <b>denosumabe</b>.'),
    ]),

    S('endo-obes', 'Obesidade e cirurgia bariátrica', [
      C('indic', 2024, 'Quais as indicações de cirurgia bariátrica citadas?',
        'IMC <b>≥ 40</b> ou IMC <b>≥ 35</b> com comorbidades graves (DM2, HAS), sobretudo após falha de tratamento clínico e comportamental.'),
      C('tecnica', 2024, 'Qual o tipo de cirurgia bariátrica com melhor resultado a médio-longo prazo?',
        'As <b>restritivo-disabsortivas</b>, como o <b>bypass gástrico em Y de Roux</b>.'),
      C('sarco', 2024, 'Obesidade sarcopênica: qual a abordagem?',
        'Farmacoterapia + <b>treinamento de força</b> + proteína <b>≥ 1,0–1,2 g/kg/dia</b>.'),
    ]),
  ],
};
