const { C, S, ul, tb } = require('./_h');

module.exports = {
  id: 'gas', nome: 'Gastro-Hepatologia', ic: '🍽️',
  desc: 'Esôfago, hepatites virais, hemocromatose e Wilson, esteatose, doenças autoimunes do fígado, hipertensão portal, nódulos hepáticos e Crohn.',
  subs: [
    S('gas-eso', 'Esôfago: Barrett, Boerhaave e motilidade', [
      C('barrett-def', 2023, 'O que é o esôfago de Barrett?',
        'Substituição do epitélio escamoso do esôfago distal por <b>epitélio colunar metaplásico</b> (gástrico e intestinal), consequência da <b>DRGE crônica</b>. Predispõe ao <b>adenocarcinoma</b>. Idade média ao diagnóstico: ~55 anos.'),
      C('barrett-sint', 2023, 'Barrett causa sintomas?',
        'A metaplasia em si <b>não</b>. Os sintomas são da DRGE (azia, regurgitação) ou de complicações: disfagia/odinofagia por úlcera ou estenose, raramente sangramento.'),
      C('barrett-bx', 2023, 'Como biopsiar a suspeita de Barrett?',
        'Pelo menos <b>4 biópsias a cada 2 cm</b> do segmento suspeito. Não biopsiar linha Z normal ou irregular com extensão &lt; 1 cm.'),
      C('barrett-rastreio', 2023, 'Em quem rastrear o esôfago de Barrett?',
        'Múltiplos fatores de risco para adenocarcinoma: hérnia hiatal, <b>≥ 50 anos</b>, <b>homem</b>, DRGE crônica, branco, obesidade central, tabagismo, parente de 1º grau com Barrett ou adenocarcinoma. A evidência é fraca: individualizar.'),
      C('barrett-displ', 2023, 'Barrett com displasia: o que fazer?',
        'Confirmar com <b>segundo patologista</b> experiente; ressecar endoscopicamente irregularidades de mucosa para graduar. Displasia de <b>alto grau</b> ou carcinoma intramucoso sem invasão da submucosa → <b>terapia de erradicação endoscópica</b>.'),
      C('boerhaave', 2022, 'Síndrome de Boerhaave: o que é e onde ocorre?',
        'Ruptura <b>transmural</b> do esôfago, em geral na porção <b>posterolateral distal intratorácica</b>, após esforço intenso ou vômitos/tosse incoercíveis. Complica com mediastinite e pneumomediastino; mortalidade alta.'),
      C('boerhaave-dp', 2022, 'Boerhaave com derrame pleural: como é o líquido?',
        '<b>Exsudato</b> com comida não digerida, <b>pH &lt; 6</b> e <b>amilase salivar elevada</b>.'),
      C('manometria', 2022, 'Manometria: qual o padrão da esclerodermia, acalasia, espasmo esofágico e paralisia faríngea?',
        tb(['Doença', 'Padrão'], ['Esclerodermia', 'Contrações de amplitude reduzida no esôfago distal; <b>EEI hipotônico</b>'], ['Acalasia', '<b>EEI hipertônico que não relaxa</b>; contrações reduzidas/simultâneas'], ['Espasmo esofágico', 'Contrações prolongadas, repetitivas, simultâneas e de grande amplitude; EEI normal'], ['Paralisia faríngea', 'Faringe e EES fracos; EES hipotônico que não relaxa bem'])),
    ]),

    S('gas-hepv', 'Hepatites virais', [
      C('tgo-tgp', 2022, 'Quais hepatites cursam com TGO &gt; TGP?',
        '<b>Febre amarela</b>, <b>hepatite alcoólica</b> e cirrose com lesão hepatocelular nova.'),
      C('hbv-def', 2022, 'Hepatite B: tipo de vírus, transmissão e cronificação?',
        'Vírus de <b>DNA</b> (Hepadnaviridae), transmissão parenteral, sexual e vertical; tropismo por hepatócitos. Cronifica em <b>5–10%</b> dos infectados (adultos).'),
      C('hbv-cronica', 2022, 'Como se diagnostica hepatite B crônica?',
        '<b>HBsAg positivo em duas medidas com intervalo de 6 meses</b>; recomenda-se confirmar com <b>HBV-DNA</b>. Fases: imunotolerante, imunorreativa, portador inativo e reativação.'),
      C('hbv-tto', 2022, 'Hepatite B crônica: qual a principal indicação de tratamento?',
        '<b>HBV-DNA ≥ 2.000 UI/mL E ALT ≥ 1,5× o limite</b>.'),
      C('hbv-tto2', 2022, 'Hepatite B crônica: quais outras situações indicam tratamento?',
        ul('Biópsia com fibrose <b>≥ F2</b> e/ou atividade <b>≥ A2</b> (METAVIR)', '<b>HBeAg reagente com idade &gt; 30 anos</b>, independente de ALT e histologia', 'História familiar de CHC', 'Coinfecção HBV/HIV, HBV/HCV ou HBV/HDV', 'Manifestações extra-hepáticas: artrite, vasculite, nefropatia, PAN, neuropatia')),
      C('hbv-aguda', 2022, 'Hepatite B aguda no adulto imunocompetente: precisa de antiviral?',
        'Em geral <b>não</b>: a maioria evolui para cura funcional. Análogo de nucleos(t)ídeo nos casos <b>graves</b>, com risco de insuficiência hepática; se houver indicação de transplante, iniciar <b>imediatamente</b>.'),
      C('hbv-vs-hcv', 2025, 'Febre, icterícia e lesão hepatocelular após sexo desprotegido: hepatite B ou C aguda?',
        '<b>Hepatite B aguda.</b> A hepatite C raramente tem quadro agudo com febre e icterícia, e a exposição típica é o uso de drogas injetáveis.'),
    ]),

    S('gas-metab', 'Hemocromatose e doença de Wilson', [
      C('hh-def', 2022, 'Hemocromatose hereditária: gene e mutações?',
        'Gene <b>HFE</b>; mutações <b>C282Y</b> e <b>H63D</b>. Doença: <b>homozigose C282Y</b> ou heterozigose composta C282Y/H63D. A forma adquirida mais importante: anemias hemolíticas crônicas.'),
      C('hh-fisio', 2022, 'Qual a fisiopatologia da hemocromatose hereditária?',
        'Mutação HFE → <b>↓ hepcidina</b> → <b>ferroportina mais ativa</b> → ↑ absorção intestinal e liberação de ferro → sobrecarga progressiva.'),
      C('hh-clin', 2022, 'Hemocromatose: quem acomete e quais as manifestações?',
        'Homens, <b>40–50 anos</b>, início insidioso (fadiga, astenia, artralgia), hepatomegalia. Os <b>6 Hs</b>: ' + ul('<b>H</b>ipogonadismo', '<b>H</b>iperpigmentação ("diabetes bronzeado")', '<b>H</b>Artrite', '<b>H</b>epatopatia (cirrose)', '<b>H</b>eart (cardiopatia)', '<b>H</b>iperglicemia (diabetes)'),
        '<b>Macete:</b> 6 Hs da hemocromatose.'),
      C('hh-triagem', 2022, 'Hemocromatose: qual o teste de triagem e por que não a ferritina?',
        '<b>Saturação de transferrina &gt; 45%</b>. A ferritina tem baixa especificidade (sobe em hepatopatias, infecções, inflamação e neoplasias), mas <b>&gt; 1.000 µg/L</b> prediz fibrose avançada.'),
      C('hh-gen', 2022, 'Hemocromatose: quem faz teste genético e quem faz biópsia?',
        'Teste genético (C282Y e H63D) em <b>todos</b> com suspeita. Biópsia hepática se <b>ferritina &gt; 1.000 µg/L</b> ou transaminases elevadas (coloração de <b>Perls / azul da Prússia</b>; índice hepático de ferro). Rastrear parentes de 1º grau (teste genético não indicado em &lt; 10 anos).'),
      C('hh-sangria', 2022, 'Hemocromatose: como fazer e monitorar a flebotomia?',
        'Retirar <b>500 mL</b> (200–250 mg de ferro) semanal ou quinzenal. Monitorar ferritina e saturação a cada 3 meses; alvo <b>ferritina 50–100 µg/L</b>. Manutenção: 500 mL a cada 3–4 meses. Melhora a cardiomiopatia; <b>não</b> melhora DM, hipogonadismo ou artropatia.'),
      C('hh-outros', 2022, 'Hemocromatose: quando usar quelantes e quando transplantar?',
        '<b>Quelantes</b> (deferoxamina, deferiprona, deferasirox): intolerância/refratariedade à flebotomia ou quando ela faz mal (anemia grave, ICC). <b>Transplante hepático</b>: doença hepática descompensada ou CHC.'),
      C('wilson-def', 2026, 'Doença de Wilson: herança, prevalência e gene?',
        'Autossômica <b>recessiva</b>, ~1:30.000. Mutação no <b>ATP7B</b> (excreção biliar do cobre e incorporação à ceruloplasmina).'),
      C('wilson-fisio', 2026, 'Qual a fisiopatologia da doença de Wilson?',
        'Cobre retido no hepatócito → lesão hepática → liberação de <b>cobre livre</b> → acúmulo no SNC, olhos e rins. Ceruloplasmina baixa e cobre livre alto. Pode causar <b>anemia hemolítica Coombs negativo</b>.'),
      C('wilson-lab', 2026, 'Doença de Wilson: como estão ceruloplasmina, cobre sérico, cobre livre e cobre urinário?',
        tb(['Exame', 'Resultado'], ['Ceruloplasmina', '<b>&lt; 20 mg/dL</b> (&lt; 15 mais específico)'], ['Cobre sérico total', '<b>Baixo</b> (pela ceruloplasmina baixa)'], ['Cobre livre', '<b>Alto</b>'], ['Cobre urinário 24 h', '<b>&gt; 100 µg/dia</b> (sobe após D-penicilamina)']),
        '<b>Armadilha:</b> o cobre sérico total está baixo, mas o livre está alto.'),
      C('wilson-dx', 2026, 'Doença de Wilson: qual escore diagnóstico e quando biopsiar ou pedir genética?',
        '<b>Escore de Leipzig ≥ 4</b> fecha o diagnóstico. RM de crânio: sinal da "<b>face do panda gigante</b>". Biópsia se o diagnóstico não fechou: cobre hepático <b>&gt; 250 µg/g</b> é compatível; entre 50 e 250 → <b>teste genético ATP7B</b> (homozigose ou heterozigose composta confirma).'),
    ]),

    S('gas-dhgna', 'Esteatose hepática (DHGNA / MASLD)', [
      C('esteatose', 2023, 'O que reduz a esteatose hepática?',
        'Atividade física aeróbica e resistida, <b>dieta mediterrânea</b>, trocar carboidrato por proteína e gordura saturada por insaturada, <b>análogos de GLP-1</b> e <b>iSGLT2</b>.'),
      C('esteato-hep', 2023, 'O que melhora a esteato-hepatite sem piorar a fibrose?',
        'Perda de peso <b>&gt; 7%</b>, <b>liraglutida e semaglutida</b> e <b>vitamina E</b> (só em pacientes <b>sem diabetes</b>).'),
      C('fibrose', 2023, 'O que melhora esteatose, esteato-hepatite e fibrose?',
        '<b>Pioglitazona</b> e <b>cirurgia bariátrica</b> (IMC &gt; 35).'),
      C('pio', 2023, 'Pioglitazona na NASH: em quem funciona e quando evitar?',
        'Evidência robusta de melhora histológica em NASH <b>com diabetes</b>. Evitar em <b>IC NYHA III–IV</b>.'),
      C('nao', 2023, 'Quais drogas NÃO são indicadas para esteatose, esteato-hepatite ou fibrose?',
        '<b>Metformina</b> e <b>orlistate</b>.',
        '<b>Armadilha:</b> metformina não trata a doença hepática.'),
    ]),

    S('gas-auto', 'Hepatite autoimune e colangite esclerosante primária', [
      C('hai', 2024, 'Qual o achado de biópsia da hepatite autoimune?',
        'Infiltrado inflamatório <b>linfoplasmocitário</b> com <b>necrose em ponte</b>.'),
      C('cep-img', 2024, 'Qual exame de imagem avalia a colangite esclerosante primária e o que mostra?',
        '<b>Colangiorressonância</b>: áreas alternadas de <b>estenose e dilatação</b> das vias biliares intra e extra-hepáticas.'),
      C('cep-rcu', 2024, 'Qual a associação da CEP e o que investigar ao diagnosticá-la?',
        '<b>Retocolite ulcerativa</b> (até 90% com biópsias de rotina). Todo paciente com CEP deve ser avaliado para <b>doença inflamatória intestinal</b>.'),
    ]),

    S('gas-hp', 'Hipertensão portal, Budd-Chiari e elastografia', [
      C('budd', 2024, 'Hipertensão portal não cirrótica em paciente jovem: lembrar de quê?',
        '<b>Síndrome de Budd-Chiari</b>: obstrução ao fluxo das <b>veias hepáticas</b>. Primária (trombose) ou secundária (compressão extrínseca, ex.: tumor).'),
      C('fibroscan', 2026, 'Elastografia hepática (FibroScan): como interpretar a rigidez?',
        tb(['Rigidez', 'Interpretação'], ['&lt; 7 kPa', 'Normal ou fibrose mínima (F0–F1)'], ['7–10 kPa', 'Fibrose significativa (F2)'], ['10–14 kPa', 'Fibrose avançada (F3)'], ['≥ 14 kPa', 'Cirrose (F4)']) + 'Pode ser feita por FibroScan, ARFI/2D-shear wave ou RM.'),
      C('varizes', 2026, 'Elastografia e plaquetas: quando dispensar endoscopia e quando indicar carvedilol?',
        '<b>&lt; 20 kPa com plaquetas &gt; 150.000</b>: risco muito baixo de varizes → pode <b>evitar endoscopia</b>. <b>≥ 25 kPa</b>: hipertensão portal clinicamente significativa → maior risco de varizes → <b>carvedilol</b>.'),
    ]),

    S('gas-nod', 'Lesões focais hepáticas', [
      C('hipovasc', 2023, 'Lesão hepática hipovascular no ultrassom: quais sítios primários pensar?',
        'Adenocarcinoma <b>gastrointestinal</b>, <b>ovariano</b> e <b>pancreático</b>. Idosa com anemia ferropriva e nódulos hepáticos hipovasculares: câncer de <b>cólon</b> metastático → <b>colonoscopia</b> com biópsia do primário.'),
      C('tc', 2023, 'TC com contraste: padrão de metástase, CHC, HNF e hemangioma?',
        tb(['Lesão', 'Padrão'], ['Metástase', 'Geralmente hipovascular; realce periférico + washout tardio'], ['CHC', '<b>Realce arterial intenso + washout precoce</b>'], ['Hiperplasia nodular focal', 'Realce arterial homogêneo + <b>cicatriz central</b>; sem washout'], ['Hemangioma', 'Realce <b>periférico nodular descontínuo</b> com preenchimento centrípeto']),
        '<b>Armadilha:</b> washout isolado não define CHC — leia o padrão dinâmico completo.'),
    ]),

    S('gas-dii', 'Doença de Crohn', [
      C('fistula', 2025, 'Crohn com ITU de repetição e pneumatúria: qual a complicação?',
        '<b>Fístula enterovesical</b> — o Crohn é transmural e fistuliza para bexiga, pele e intestino.'),
      C('entero-rm', 2025, 'Qual o exame mais sensível para fístulas e extensão da inflamação no Crohn?', '<b>Entero-RM.</b>'),
      C('rcu', 2025, 'Por que a retocolite raramente fistuliza?', 'A inflamação é restrita à <b>mucosa</b>.'),
      C('suspeita', 2026, 'Anos de diarreia, dor abdominal, emagrecimento, anemia e hipovitaminose D: o que sugere?',
        '<b>Doença inflamatória intestinal</b>, como a <b>doença de Crohn</b>.'),
    ]),
  ],
};
