const { C, S, ul, tb, svgFluxo } = require('./_h');

module.exports = {
  id: 'hem', nome: 'Hematologia', ic: '🩸',
  desc: 'Anemias, hemólise, aplasia, linfomas, leucemias, discrasias plasmocitárias, coagulação e eosinofilia.',
  subs: [
    S('hem-micro', 'Anemias microcíticas e anemia de doença crônica', [
      C('adc-reti', 2025, 'Na anemia de doença crônica, a contagem de reticulócitos está aumentada ou reduzida?',
        '<b>Reduzida.</b> A anemia de doença crônica é hipoproliferativa.'),
      C('adc-lab', 2025, 'Qual o perfil laboratorial da anemia de doença crônica?',
        ul('Anemia <b>normocítica ou microcítica</b>', 'Ferro sérico <b>reduzido</b>', 'Saturação de transferrina <b>normal ou reduzida</b>', 'TIBC (capacidade total de ligação do ferro) <b>normal ou reduzida</b>')),
      C('adc-causas', 2025, 'Quais grupos de doenças causam anemia de doença crônica?',
        'Infecções crônicas, doenças autoimunes e neoplasias sólidas.'),
      C('fe-vs-adc', 2025, 'Ferropriva × doença crônica: qual exame do perfil de ferro separa as duas?',
        '<b>TIBC.</b>' + tb(['', 'Ferropriva', 'Doença crônica'], ['Ferro sérico', '↓', '↓'], ['Sat. transferrina', '↓', 'N ou ↓'], ['Ferritina', '↓', '—'], ['TIBC', '<b>↑</b>', '<b>N ou ↓</b>']),
        '<b>Armadilha:</b> ferro e saturação baixos aparecem nas duas; a TIBC alta é da ferropriva.'),
      C('sidero', 2025, 'Como estão os estoques de ferro na anemia sideroblástica?', 'Normais ou <b>elevados</b>.'),
      C('talass', 2025, 'Anemia microcítica e hipocrômica com RDW normal: qual o diagnóstico a pensar e o achado da eletroforese?',
        '<b>Beta-talassemia minor.</b> Na eletroforese de hemoglobina: <b>HbA2 &gt; 3%</b>.',
        '<b>Macete:</b> micro + RDW normal = talassemia (a ferropriva costuma ter RDW alto).'),
      C('causas', 2025, 'Quais as causas de microcitose citadas?',
        ul('Deficiência de ferro', 'Anemia de doença crônica', 'Talassemia', 'Intoxicação por chumbo', 'Anemia sideroblástica')),
      C('epo', 2026, 'A eritropoetina é indicada em qual anemia e em qual não é?',
        'Indicada na anemia de <b>doença crônica / associada à doença renal crônica</b>. <b>Não</b> é indicada na anemia <b>ferropriva</b>.'),
    ]),

    S('hem-macro', 'Anemias macrocíticas: B12 e folato', [
      C('achados', 2022, 'Quais achados sugerem deficiência de vitamina B12 ou ácido fólico?',
        ul('VCM &gt; 115 fL', 'Leucopenia', 'Plaquetopenia', 'Neutrófilos hipersegmentados', 'Sintomas neurológicos', 'Vegetariano sem suplementar B12')),
      C('hcy-amm', [2022, 2026], 'Homocisteína e ácido metilmalônico: quais sobem na deficiência de B12 e quais na de folato?',
        tb(['', 'Def. B12', 'Def. folato'], ['Homocisteína', '↑', '↑'], ['Ácido metilmalônico', '<b>↑</b>', 'normal']),
        '<b>Macete:</b> o ácido metilmalônico é o marcador exclusivo da B12.'),
      C('b12-neuro', 2026, 'Paciente com anemia e sintomas neurológicos por falta de B12: como estão ácido metilmalônico e homocisteína?',
        'Os <b>dois elevados</b>.'),
      C('causas', 2022, 'Quais as causas de macrocitose citadas?',
        ul('Deficiência de B12 e de ácido fólico', 'Hipotireoidismo', 'Síndromes mielodisplásicas', 'Infecção pelo HIV', 'Deficiência de cobre/zinco', 'Medicações: metformina, fenitoína, metotrexato, zidovudina, hidroxiureia')),
      C('mtx', 2026, 'Anemia pelo uso de metotrexato: qual VCM esperar e por quê?',
        'VCM <b>&gt; 100 fL</b> (macrocítica), porque decorre de <b>deficiência de ácido fólico</b>.'),
      C('gastrite', 2022, 'O que a gastrite atrófica autoimune causa e qual o risco oncológico associado?',
        'Hipocloridria e <b>menor produção de fator intrínseco</b> → má absorção de B12 → <b>anemia perniciosa</b>. Risco de <b>carcinoma gástrico 3×</b> maior.'),
    ]),

    S('hem-hemol', 'Anemias hemolíticas: esferocitose, HPN e G6PD', [
      C('esf-clin', 2022, 'Quais as principais manifestações clínicas da esferocitose?',
        ul('Anemia hemolítica intensa', 'Esplenomegalia sintomática', 'Litíase biliar por cálculos <b>pigmentados</b>', 'Úlceras maleolares', 'Massas paravertebrais (hematopoese extramedular)')),
      C('esf-lab', 2022, 'Quais achados laboratoriais esperar na esferocitose?',
        'Marcadores de hemólise, <b>esferócitos</b> no esfregaço, <b>Coombs negativo</b> e <b>CHCM aumentado</b>.'),
      C('esf-dx', 2022, 'Qual o teste diagnóstico da esferocitose citado?', '<b>Teste de fragilidade osmótica.</b>'),
      C('hpn-clin', 2022, 'Qual a clínica da hemoglobinúria paroxística noturna (HPN)?',
        'Dor abdominal, cefaleia, febre, <b>hemoglobinúria à noite</b> (hemólise intravascular) e <b>hipercoagulabilidade</b>, com tromboses venosas em veias hepáticas, cerebrais e intra-abdominais.'),
      C('hpn-triade', 2022, 'Qual a tríade típica da HPN?',
        'Anemia hemolítica <b>com ferropenia</b> + <b>pancitopenia</b> + <b>trombose venosa</b>.',
        '<b>Macete:</b> hemólise + citopenias + trombose em sítio incomum = HPN.'),
      C('hpn-evol', 2022, 'Para quais doenças a HPN pode evoluir?', 'Leucemia aguda ou anemia aplásica.'),
      C('hpn-dx', 2022, 'Como se faz o diagnóstico da HPN?',
        'Hoje: <b>citometria de fluxo</b>, pesquisando <b>CD55/CD59</b> na superfície de hemácias ou granulócitos (método preferencial). Antigo: <b>teste de HAM</b> (hemácias do paciente em soro normal acidificado → o complemento ativa e lisa as hemácias anormais).'),
      C('hpn-tto', 2022, 'Qual o tratamento da HPN?',
        '<b>Eculizumabe</b> (anticorpo <b>anti-C5</b>, inibe a ativação do complemento). Suporte conforme o caso: corticoide, ferro e ácido fólico, transfusões, eritropoetina, anticoagulantes, trombolíticos, transplante alogênico.'),
      C('g6pd', 2023, 'Deficiência de G6PD: quais achados no sangue periférico e em que contexto suspeitar?',
        'Anemia hemolítica com <b>bite cells</b> e <b>corpúsculos de Heinz</b>. Pensar quando os sintomas surgem após <b>introdução de medicação nova</b>. É o defeito enzimático hereditário mais comum das hemácias.'),
    ]),

    S('hem-aplas', 'Pancitopenia e anemia aplástica', [
      C('quando', 2022, 'Quando pensar em anemia aplástica?',
        'Pancitopenia com febre, sangramentos ou equimoses, <b>sem esplenomegalia e sem linfadenopatia</b>.'),
      C('mo', 2022, 'O que mostra a biópsia de medula na anemia aplástica?',
        'Medula <b>hipocelular</b>: menos de <b>30%</b> ocupada por células hematopoiéticas, o restante é tecido adiposo.'),
      C('dd', 2023, 'Jovem com pancitopenia macrocítica e reticulocitopenia, sem hemólise e sem displasia no sangue: quais os 3 diagnósticos diferenciais e qual fica?',
        ul('<b>SMD</b>: improvável — paciente muito jovem e sem displasia na hematoscopia', '<b>Deficiência de B12</b>: improvável — sem sinais de eritropoese ineficaz (DHL e bilirrubinas normais)', '<b>Anemia aplástica</b>: hipótese principal')),
      C('grave', 2023, 'Como se define anemia aplástica grave?',
        'Medula hipocelular com pelo menos 2 destes: ' + ul('Reticulócitos &lt; 60 mil/mm³ (contagem automatizada)', 'Neutrófilos &lt; 500/mm³', 'Plaquetas &lt; 20 mil/mm³') +
        'Na sua anotação os três aparecem ligados por "ou"; no critério clássico (Camitta) são necessários dois.'),
      C('tto', 2023, 'Anemia aplástica grave: qual o tratamento conforme a idade?',
        '<b>&lt; 40 anos</b>: transplante de medula óssea em 1ª linha. <b>&gt; 40 anos</b>: imunossupressão.'),
    ]),

    S('hem-smd', 'Síndrome mielodisplásica', [
      C('volume', 2022, 'A mielodisplasia cursa com microcitose ou macrocitose?', '<b>Macrocitose.</b>'),
      C('clin', 2022, 'Qual o quadro clínico da síndrome mielodisplásica?',
        'Inespecífico: fadiga, sangramentos, febre, pancitopenia e perda ponderal na doença avançada.'),
      C('mo', 2022, 'Quais alterações na medula óssea da SMD?',
        'Megaloblastose, <b>sideroblastos em anel</b> e hipogranulação da linhagem mieloide ou megacariocítica.'),
      C('sp', 2022, 'Quais alterações no sangue periférico da SMD?',
        ul('Hemácias displásicas: macro-ovalócitos, eliptócitos, acantócitos, estomatócitos, dacriócitos com pontilhado basofílico, corpúsculos de Pappenheimer', 'Plaquetas dismórficas', 'Neutrófilos hipossegmentados e hipogranulares (<b>pseudo-Pelger-Huët</b>)')),
      C('risco', 2022, 'Por que o paciente com SMD tem risco infeccioso elevado e qual a base do tratamento citada?',
        'Pela <b>neutropenia e disfunção granulocitária</b>. O tratamento citado baseia-se em <b>medidas de suporte</b>.'),
    ]),

    S('hem-poli', 'Policitemia', [
      C('divisor', 2023, 'Qual o exame "divisor de águas" na investigação de policitemia?',
        '<b>Eritropoetina sérica.</b>' + svgFluxo('Investigação de policitemia pela eritropoetina',
          [{ x: 110, y: 6, w: 120, h: 30, t: ['EPO sérica'], cor: 'azul' },
           { x: 8, y: 66, w: 150, h: 44, t: ['EPO aumentada:', 'policitemia secundária'], cor: 'ouro' },
           { x: 182, y: 66, w: 150, h: 44, t: ['EPO normal ou baixa:', 'investigar PV (JAK2)'], cor: 'verde' },
           { x: 8, y: 132, w: 150, h: 44, t: ['hipóxia ou tumor', 'produtor de EPO'], cor: 'claro' }],
          [[150, 36, 90, 64], [190, 36, 250, 64], [83, 110, 83, 130]])),
      C('secundaria', 2023, 'Policitemia com EPO elevada, sem hipóxia, sem tabagismo e sem comorbidades: o que investigar e com qual exame?',
        'A principal causa de policitemia secundária é a hipóxia; sem ela, pesquisar <b>tumores abdominais/pélvicos produtores de EPO</b> — <b>TC de abdome</b>.'),
      C('jak2', 2023, 'Em quem pesquisar a mutação JAK2?',
        'Em quem tem achados clínicos de neoplasia mieloproliferativa e em quem tem <b>EPO normal ou baixa</b> (sugere policitemia primária).'),
      C('pv', 2023, 'Quais os critérios diagnósticos de policitemia vera citados?',
        'Aumento de Hb/Ht, biópsia de medula com <b>hipercelularidade</b> e mutação do gene <b>JAK2</b>.'),
    ]),

    S('hem-leuc', 'Leucemias: LMC, leucostase e tricoleucemia', [
      C('lmc', 2023, 'Leucocitose com desvio à esquerda, basofilia e esplenomegalia: qual diagnóstico obrigatório?',
        '<b>Leucemia mieloide crônica (LMC).</b>',
        '<b>Macete:</b> basofilia + esplenomegalia + desvio à esquerda = LMC.'),
      C('lmc-vs-lzm', 2023, 'Esplenomegalia com linfocitose × esplenomegalia com leucocitose, desvio à esquerda e basofilia: o que cada uma sugere?',
        'Linfocitose → <b>linfoma de zona marginal esplênico</b>. Leucocitose com desvio e basofilia → <b>LMC</b>.'),
      C('leucostase', 2023, 'Paciente com leucostase: qual a medida inicial mais importante?',
        '<b>Citorredução imediata</b>, junto com a prevenção de síndrome de lise tumoral (hidratação vigorosa). Sem leucoaférese disponível: <b>hidroxiureia ou quimioterapia de indução</b>.',
        '<b>Armadilha:</b> hidratar é necessário (risco altíssimo de SLT), mas a prioridade é reduzir os leucócitos.'),
      C('hcl-clin', 2022, 'Como se manifesta a leucemia de células pilosas (tricoleucemia)?',
        'Sintomas de <b>esplenomegalia ou citopenias</b>: fadiga, infecções, sangramentos. <b>Linfadenopatia e hepatomegalia geralmente ausentes.</b>'),
      C('hcl-dx', 2022, 'Tricoleucemia: achado no sangue periférico, exames diagnósticos e o que acontece no aspirado de medula?',
        '"<b>Hairy cells</b>" (células mononucleares pilosas). Biópsia e aspirado de medula com imunofenotipagem/citometria de fluxo. O aspirado é <b>seco</b> (punção branca) pela fibrose difusa.'),
    ]),

    S('hem-linf', 'Linfomas', [
      C('burkitt-def', 2024, 'O que é o linfoma de Burkitt?',
        'Linfoma de <b>células B maduras</b>, altamente agressivo, com altíssima taxa de proliferação e sintomas agudos que pioram rápido sem tratamento.'),
      C('burkitt-formas', 2024, 'Quais as três formas do linfoma de Burkitt e como se apresentam?',
        tb(['Forma', 'Apresentação'], ['Endêmica', 'Crianças, sobretudo na África; tumores em <b>ossos da face e mandíbula</b>'], ['Esporádica', 'Sem idade ou região preferencial; <b>grandes massas abdominais</b>'], ['Imunodeficiência', 'Associada ao <b>HIV</b>; adenomegalia + acometimento extranodal'])),
      C('burkitt-lab', 2024, 'Burkitt: quais achados clínico-laboratoriais e como se diagnostica?',
        'Linfonodomegalia, linfocitose, sintomas B, <b>DHL alto</b> e <b>lise tumoral</b>. Diagnóstico por <b>biópsia</b> do sítio acometido.'),
      C('lzm-sub', [2023, 2024], 'Quais os subtipos de linfoma de zona marginal e qual o mais comum?',
        'Extranodal (<b>MALT</b>), nodal e esplênico — todos indolentes, de células B. O mais comum é o <b>MALT gástrico</b>, muito associado ao <b>H. pylori</b>.'),
      C('lzm-apres', 2024, 'Como se apresenta cada subtipo de linfoma de zona marginal?',
        tb(['Subtipo', 'Apresentação'], ['MALT', 'Massa única extranodal no sítio de mucosa (estômago, intestino, salivar, pulmão) ou lesão ulcerada gástrica'], ['Nodal', 'Restrito a adenomegalias'], ['Esplênico', '<b>Esplenomegalia de grande monta</b> + medula óssea e sangue periférico'])),
      C('lzm-esp-dx', 2023, 'Linfoma de zona marginal esplênico: como se faz o diagnóstico?',
        'Biópsia de medula óssea; se inconclusiva e a suspeita persistir, <b>esplenectomia</b> (diagnóstica e terapêutica).'),
      C('angio-def', 2024, 'Linfoma angioimunoblástico: qual a célula de origem e qual a marca clínica?',
        'Linfócito <b>T helper folicular (TFH)</b>. Por isso cursa com <b>reação inflamatória intensa e desregulação imune</b>: fenômenos pró-inflamatórios e autoimunes.'),
      C('angio-clin', 2024, 'Quais as manifestações clínicas do linfoma angioimunoblástico?',
        'Adenomegalia, hepatoesplenomegalia, sintomas B (febre, sudorese noturna, perda &gt; 10% do peso), <b>rash cutâneo</b>, fenômenos autoimunes e infiltração medular.'),
      C('angio-lab', 2024, 'Quais alterações laboratoriais no linfoma angioimunoblástico?',
        'Pode imitar doença autoimune: VHS alto, <b>FAN e FR positivos</b>, DHL alto, <b>Coombs direto positivo</b>, citopenias, <b>gamopatia policlonal</b> e <b>hipereosinofilia</b>.'),
      C('angio-prog', 2024, 'Linfoma angioimunoblástico: diagnóstico, prognóstico e tratamento?',
        'Biópsia (geralmente de linfonodo) com imuno-histoquímica. Agressivo, sobrevida em 5 anos de <b>~30%</b>. Poliquimioterapia: boa resposta inicial, recaídas frequentes.'),
      C('gast-etio', 2024, 'Quais as duas etiologias principais do linfoma gástrico primário?',
        '<b>Linfoma difuso de grandes células B (LDGCB)</b> e <b>linfoma MALT</b>.'),
      C('gast-ldgcb', 2024, 'LDGCB gástrico: comportamento, achados e tratamento?',
        'Agressivo, manifestação nodal e/ou extranodal; sintomas B e <b>DHL elevado em até 50%</b>. O <b>estômago é o sítio extranodal mais frequente</b>. Tratamento: quimioterapia.'),
      C('gast-malt', 2024, 'Linfoma MALT gástrico: comportamento, associação e tratamento?',
        'Indolente e localizado. Associação direta com <b>H. pylori</b>. Tratamento conforme estadiamento e infecção: <b>erradicação do H. pylori</b>, radioterapia local e/ou quimioterapia.'),
      C('gast-vs-adeno', 2024, 'Úlcera gástrica com DHL muito alto e evolução rápida: linfoma ou adenocarcinoma?',
        'Favorece <b>linfoproliferação</b>. DHL muito alto e evolução aguda não combinam com adenocarcinoma. A úlcera também é pouco compatível com o adenocarcinoma difuso (que infiltra, sem úlcera).'),
      C('snc', 2024, 'Linfoma primário do SNC: tipo histológico, fatores de risco e clínica?',
        'Geralmente <b>DGCB</b>, 50–60 anos. Fatores: <b>imunossupressão</b> e <b>EBV</b>. Déficits neurológicos agudos e sinais de hipertensão intracraniana.'),
      C('snc-img', 2024, 'Linfoma primário do SNC: como aparece na imagem?',
        'Uma ou mais lesões com <b>restrição à difusão</b> e <b>edema perilesional leve</b>, em região <b>periventricular</b>, substância branca profunda, <b>corpo caloso</b> e núcleos da base.'),
      C('snc-dx', 2024, 'Linfoma primário do SNC: como diagnosticar e tratar?',
        'Diagnóstico por <b>biópsia</b>. Tratamento: poliquimioterapia à base de <b>metotrexato</b>.'),
    ]),

    S('hem-plasmo', 'Discrasias plasmocitárias: Waldenström e POEMS', [
      C('wm-def', 2025, 'O que é a macroglobulinemia de Waldenström?',
        'Doença linfoproliferativa com produção clonal de <b>IgM</b> — também chamada <b>linfoma linfoplasmocítico</b>. Idosos. Mutação <b>MYD88 em &gt; 90%</b>.'),
      C('wm-clin', 2025, 'Quais os sintomas clássicos da macroglobulinemia de Waldenström?',
        '<b>Síndrome de hiperviscosidade</b> e fenômenos autoimunes: <b>neuropatia periférica</b> e anemia hemolítica autoimune.'),
      C('wm-lab', 2025, 'Qual o achado da eletroforese de proteínas na Waldenström?',
        'Pico monoclonal às custas de <b>IgM</b> na eletroforese com imunofixação.'),
      C('hiperv', 2025, 'Síndrome de hiperviscosidade: como se manifesta e como se trata?',
        'Cefaleia, turvação visual, sangramento e <b>hemorragia retiniana</b> no fundo de olho. Tratamento: <b>plasmaférese</b>.'),
      C('poems-def', 2024, 'O que é a síndrome POEMS e quem acomete?',
        'Síndrome paraneoplásica secundária a uma <b>discrasia plasmocitária</b>. Rara, indolente, pacientes por volta dos 60 anos.'),
      C('poems-mand', 2024, 'Quais os critérios mandatórios da POEMS?', '<b>Polineuropatia</b> + <b>paraproteinemia</b> (proteína monoclonal).'),
      C('poems-crit', 2024, 'POEMS: quais os critérios maiores e menores citados?',
        '<b>Maiores</b>: <b>VEGF elevado</b> e <b>lesão óssea esclerótica</b>. <b>Menores</b>: organomegalia, sobrecarga volêmica, endocrinopatia, lesões cutâneas, papiledema, plaquetose/policitemia.',
        '<b>Macete:</b> polineuropatia + VEGF alto + lesão óssea esclerótica diferenciam a POEMS das outras polineuropatias.'),
      C('poems-tto', 2024, 'Qual o tratamento da POEMS?', 'Radioterapia e/ou quimioterapia, conforme a extensão da infiltração plasmocitária.'),
    ]),

    S('hem-sam', 'Síndrome de ativação macrofágica (HLH)', [
      C('def', 2024, 'Qual a fisiopatologia da SAM/HLH?',
        'Resposta citotóxica de <b>células NK e linfócitos prejudicada</b> → inflamação sem controle → <b>tempestade de citocinas</b> e disfunção orgânica.'),
      C('suspeita', [2024, 2025], 'Quando a SAM/HLH deve ser descartada?',
        'Diante de síndrome inflamatória <b>hiperferritinêmica com bicitopenia</b>, ou queda abrupta das células do sangue num paciente inflamado (ex.: doença de Still).'),
      C('familiar', 2024, 'SAM familiar × adquirida: causas e tratamento?',
        '<b>Familiar</b>: mutações genéticas; tratamento definitivo é o <b>TCTH</b>. <b>Adquirida</b>: infecções, neoplasias e doenças inflamatórias (autoimunes/autoinflamatórias); tratar com <b>etoposídeo, ciclosporina e dexametasona</b> + controle da causa.'),
    ]),

    S('hem-plaq', 'Púrpura trombocitopênica imune (PTI)', [
      C('def', 2025, 'O que é a PTI e o que pode desencadeá-la?',
        'Destruição de plaquetas por <b>autoanticorpos</b>. Gatilhos: infecções virais (<b>hepatite C, B, HIV, EBV</b>), doenças autoimunes e linfoproliferativas (linfoma, LLC).'),
      C('dx', 2025, 'Como se faz o diagnóstico da PTI e como se apresenta?',
        'Diagnóstico de <b>exclusão</b> de outras causas de plaquetopenia. Sangramento <b>mucocutâneo</b>: petéquias, gengivorragia, epistaxe.'),
      C('tto', 2025, 'Quando tratar a PTI?',
        'Com sangramento pela plaquetopenia ou plaquetas em nível de risco hemorrágico: <b>&lt; 20.000–30.000/mm³</b>.'),
    ]),

    S('hem-coag', 'Coagulação: CIVD, teste da mistura e hemofilia adquirida', [
      C('civd-def', 2022, 'O que é a CIVD?',
        'Aumento anormal da <b>coagulação (trombina)</b> e da <b>fibrinólise</b> ao mesmo tempo → trombose e sangramento.'),
      C('civd-causas', 2022, 'Quais as causas mais comuns de CIVD?',
        'Infecções graves/sepse, complicações obstétricas (aborto retido, pré-eclâmpsia) e neoplasias ativas.'),
      C('civd-lab', 2022, 'Qual o laboratório da CIVD?',
        'Plaquetopenia por consumo, <b>TP e TTPa alargados</b>, <b>fibrinogênio reduzido</b>, <b>D-dímero aumentado</b>. Pode haver anemia microangiopática (esquizócitos).',
        '<b>Armadilha:</b> fatores de coagulação normais não combinam com CIVD — há consumo em toda a cascata.'),
      C('mistura', 2023, 'Teste da mistura: quando o TTPa corrige e quando não corrige?',
        '<b>Corrige</b> quando falta fator (deficiência de fator VIII, IX, von Willebrand, vitamina K, fator X…). <b>Não corrige</b> quando há <b>inibidor</b> (ex.: anticorpo anti-fator VIII da hemofilia A adquirida).' +
        '<br><br>Sua anotação diz "não corrige hemofilias": vale para a hemofilia <b>adquirida</b> (com inibidor); na hemofilia congênita, que é falta de fator, a mistura corrige.',
        '<b>Armadilha:</b> não corrigiu = inibidor, não deficiência.'),
      C('ha-vs-hc', 2023, 'Hemofilia A adquirida × hemofilia A clássica: qual a diferença?',
        '<b>Adquirida</b>: autoanticorpo <b>anti-fator VIII</b>; trata com <b>imunossupressão</b>. <b>Clássica</b>: deficiência hereditária do fator; trata com <b>reposição de fator</b>.'),
      C('ha-tto', 2023, 'Hemofilia A adquirida: como tratar o sangramento e o inibidor?',
        ul('Sangramento leve: <b>DDAVP</b> (libera fator de von Willebrand)', 'Moderado/grave com <b>baixo título</b> de inibidor: <b>fator VIII recombinante em altas doses</b>', 'Moderado/grave com <b>alto título</b>: <b>complexo protrombínico ativado</b> ou <b>fator VII</b>', 'Erradicar o inibidor: <b>ciclofosfamida + corticoide</b> (pode sumir sozinho)')),
    ]),

    S('hem-mat', 'Microangiopatias trombóticas: SHU', [
      C('def', 2023, 'Qual a tríade da síndrome hemolítico-urêmica e o que a diferencia das outras MAT?',
        'Anemia hemolítica microangiopática + trombocitopenia + <b>insuficiência renal aguda</b> (geralmente grave, creatinina &gt; 2). O <b>predomínio renal</b> a diferencia da PTT.'),
      C('tipos', 2023, 'SHU típica × atípica: frequência e mecanismo?',
        tb(['', 'Típica', 'Atípica'], ['Frequência', '~90%', '~10%'], ['Mecanismo', 'Bactéria produtora de <b>toxina Shiga</b>, precedida de diarreia', 'Ativação desregulada da <b>via alternativa do complemento</b> (ex.: deficiência de fator H)'])),
    ]),

    S('hem-eos', 'Eosinofilia', [
      C('grau', 2026, 'Como se classifica a eosinofilia?',
        tb(['Grau', 'Eosinófilos/mm³'], ['Leve', '500–1.500'], ['Moderada', '1.500–5.000'], ['Grave (hipereosinofilia)', '&gt; 5.000'])),
      C('pacto', 2026, 'Qual o mnemônico das causas de eosinofilia?',
        '<b>PACTO</b>: ' + ul('<b>P</b>arasitoses', '<b>A</b>lergias (asma, rinite, dermatite atópica, reações a fármacos)', '<b>C</b>onectivopatias/vasculites: GEPA (Churg-Strauss)', '<b>T</b>umores (linfoma de Hodgkin, leucemias)', '<b>O</b>utros (insuficiência adrenal, esofagite eosinofílica)'),
        '<b>Macete:</b> PACTO — Parasitas, Alergia, Conectivopatia, Tumor, Outros.'),
      C('santa', 2026, 'Quais parasitas têm ciclo pulmonar?',
        '<b>SANTA</b>: <b>S</b>trongyloides, <b>A</b>ncylostoma, <b>N</b>ecator, <b>T</b>oxocara, <b>A</b>scaris.',
        '<b>Macete:</b> SANTA.'),
    ]),
  ],
};
