const { C, S, ul, tb } = require('./_h');

module.exports = {
  id: 'inf', nome: 'Infectologia', ic: '🦠',
  desc: 'Antimicrobianos, cateter e candidemia, micoses, HIV, sífilis, TB, imunossuprimido, infecções graves, influenza e diarreias.',
  subs: [
    S('inf-atb', 'Antimicrobianos: Pseudomonas e tigeciclina', [
      C('tige', 2025, 'Tigeciclina: por que é uma "pegadinha" no antibiograma?',
        'In vitro cobre gram-positivos (Enterococcus, inclusive <b>VRE</b>, Listeria, estreptococos, <b>MSSA e MRSA</b>) e aparece no antibiograma, mas <b>na prática não é usada para eles</b>: o uso clínico é focado em <b>gram-negativos</b>.',
        '<b>Armadilha:</b> o que funciona no laboratório nem sempre é o que se usa na clínica.'),
      C('tige-uso', 2025, 'Quais os principais usos clínicos da tigeciclina?',
        'Infecções intra-abdominais, pneumonias, pele e partes moles e, nos últimos anos, <b>Acinetobacter baumannii multirresistente</b> em casos refratários com poucas opções.'),
      C('pseudo-sim', 2025, 'Quais antimicrobianos cobrem Pseudomonas?',
        ul('Penicilina: <b>piperacilina-tazobactam</b>', 'Cefalosporinas: <b>ceftazidima</b> (e ceftolozane-tazobactam); cefepime', 'Carbapenêmicos: <b>imipenem e meropenem</b>', 'Quinolonas: <b>ciprofloxacino, levofloxacino</b>', 'Polimixinas: colistina e polimixina B', 'Aminoglicosídeos: amicacina e gentamicina')),
      C('pseudo-nao', 2025, 'Quais antimicrobianos NÃO cobrem Pseudomonas?',
        '<b>Ertapenem</b> e <b>tigeciclina</b> (resistência intrínseca), além dos exclusivos para gram-positivos: vancomicina, teicoplanina, linezolida, daptomicina.',
        '<b>Macete:</b> o único carbapenêmico que não pega Pseudomonas é o ertapenem.'),
      C('quinolona', 2025, 'Qual classe surgiu como a grande promessa contra Pseudomonas?', 'As <b>quinolonas</b> (ciprofloxacino, levofloxacino).'),
      C('por-germe', 2022, 'Antibiótico conforme o germe isolado na hemocultura:',
        tb(['Germe', 'Escolha'], ['S. aureus MSSA', 'Oxacilina / cefazolina'], ['S. aureus MRSA', 'Vancomicina'], ['Enterococo sensível à ampicilina', 'Ampicilina'], ['Enterococo resistente à ampicilina', 'Vancomicina'], ['Enterococo resistente à vancomicina', 'Daptomicina / linezolida'], ['Enterobactéria ESBL negativa', 'Ceftriaxona'], ['Enterobactéria ESBL positiva', 'Carbapenêmico'], ['Pseudomonas', 'Ceftazidima / cefepime / pip-tazo']) +
        'Sua tabela dizia "enterococo sensível/resistente à meticilina → oxacilina". O enterococo é naturalmente resistente à oxacilina; o marcador é a <b>ampicilina</b>.'),
    ]),

    S('inf-cvc', 'Infecção de cateter e candidemia', [
      C('cand-cateter', 2022, 'Cresceu Candida em hemocultura de paciente com cateter: o que fazer com o cateter?',
        '<b>Retirar sempre</b>, pelo risco de manter embolização e disseminação.'),
      C('cand-inicio', 2022, 'Quando iniciar o antifúngico na candidemia e qual classe preferir?',
        '<b>Imediatamente</b> ao isolar Candida no sangue, mesmo sem a espécie. Preferir <b>equinocandinas</b>, sobretudo em neutropênicos.'),
      C('cand-porque', 2022, 'Por que equinocandina e não fluconazol no início da candidemia?',
        'Infecção grave e existência de espécies <b>resistentes ao fluconazol</b>: <b>C. glabrata</b> e <b>C. krusei</b>.'),
      C('cand-duracao', 2022, 'Candidemia: quando passar para fluconazol e quanto tempo tratar?',
        'Após identificar a espécie ou melhora clínica com recuperação dos neutrófilos → <b>fluconazol</b>. Tratar por <b>14 dias após a primeira hemocultura negativa</b> (culturas a cada 48 h).'),
      C('lock', 2022, 'Quando remover o cateter e contraindicar a terapia de lock?',
        ul('Germes: <b>S. aureus, Pseudomonas aeruginosa, Candida</b>', 'Instabilidade hemodinâmica', 'Endocardite ou outra infecção à distância', 'Infecção subcutânea no óstio do cateter', 'Tromboflebite supurativa', 'Bacteremia persistente após 72 h de antibiótico adequado')),
      C('endoc', 2022, 'Em infecção de cateter, quando investigar infecção à distância (endocardite)?',
        ul('Germes: S. aureus, Pseudomonas, Candida', 'Cateter não removido', 'Implantes valvares ou ortopédicos', 'Suspeita de endocardite, osteomielite, tromboflebite ou doença fúngica')),
    ]),

    S('inf-fung', 'Micoses e antifúngicos', [
      C('histo', 2022, 'Como se faz o diagnóstico da histoplasmose pulmonar?',
        'Forma <b>aguda</b>: antígeno e cultura. Forma <b>crônica</b>: sorologia e cultura.'),
      C('cripto', 2022, 'Como se faz o diagnóstico da criptococose pulmonar?',
        '<b>Imunocompetente</b>: cultura. <b>Imunossuprimido</b>: antígeno e cultura — e <b>sempre avaliar o líquor</b> se positivo.'),
      C('azois', 2022, 'Triazóis (fluconazol, voriconazol): qual a limitação e qual a indicação clássica do voriconazol?',
        'Grande parte não é boa para <b>C. glabrata e C. krusei</b> (principalmente o fluconazol). Voriconazol: tratamento da <b>aspergilose invasiva</b>.'),
      C('anfo', 2022, 'Anfotericina B: espectro e uso?',
        'Amplo: Candida, Aspergillus, <b>Cryptococcus</b>, <b>Mucorales</b>. Infecções fúngicas graves e sistêmicas, principalmente em imunossuprimidos.'),
      C('equino', 2022, 'Equinocandinas (caspofungina): o que cobrem e o que não cobrem?',
        'Excelentes contra <b>Candida</b> (inclusive resistentes a azólicos). <b>Não cobrem Cryptococcus nem Mucorales.</b>'),
    ]),

    S('inf-pcm', 'Paracoccidioidomicose', [
      C('transm', 2022, 'Como se adquire a paracoccidioidomicose?',
        'Inalação de <b>conídios</b> do solo e poeira, que viram <b>leveduras</b> no pulmão (multibrotamento). Pode haver inoculação em acidente de laboratório. <b>Não há transmissão inter-humana</b> nem de animais. Incubação: 6 semanas a ~4 meses.'),
      C('mulher', 2022, 'Por que a PCM é rara em mulheres adultas e como é quando ocorre?',
        'Os <b>estrógenos</b> inibem a transformação do fungo em levedura. As mulheres que adoecem tendem a ter a forma <b>mais disseminada</b>.'),
      C('imuno', 2022, 'Qual a imunidade que controla a PCM e quem tem reativação?',
        'Imunidade <b>celular (linfócito T)</b>. Reativação de focos antigos com imunidade deprimida: aids, neoplasias, transplantados, imunossupressão.'),
      C('clin', 2022, 'Quais as manifestações da forma com envolvimento do sistema reticuloendotelial?',
        'Linfadenomegalia localizada ou generalizada que pode <b>supurar e fistulizar</b>, hepatoesplenomegalia, manifestações digestivas, lesões de pele/mucosa, osteoarticulares; febre e emagrecimento. Linfonodos abdominais podem formar <b>massas que comprimem colédoco e alças</b>. Pulmão raramente.'),
      C('cronica', 2022, 'Qual a forma responsável pela maioria dos casos de PCM?', 'A <b>forma crônica</b>: 74–96% dos casos.'),
      C('dx', 2022, 'Qual o padrão-ouro diagnóstico da PCM?',
        '<b>Exame micológico direto e cultura</b> (escarro, raspado de lesão, aspirado de linfonodo, em KOH): leveduras com brotamento múltiplo, birrefringentes. Sorologia recomendada: <b>imunodifusão dupla em gel de ágar</b> (S &gt; 80%, E &gt; 90%).'),
      C('tto', 2022, 'Qual o tratamento da PCM?',
        ul('Leve: <b>itraconazol 200 mg/dia</b>', 'Moderada: itraconazol 200 mg 12/12 h', 'Duração mínima de <b>12 meses</b> (alternativa: sulfametoxazol-trimetoprim 800/160 mg 8/8 ou 12/12 h)', 'Grave: <b>anfotericina B lipídica</b> 3–5 mg/kg/dia por 2–4 semanas, depois manutenção como na leve/moderada')),
    ]),

    S('inf-hiv', 'HIV: Sarcoma de Kaposi e angiomatose bacilar', [
      C('sk-formas', 2024, 'Quais as formas clínicas do Sarcoma de Kaposi?',
        ul('Cutâneo limitado: <b>&lt; 20 lesões</b>', 'Cutâneo disseminado: <b>&gt; 20 lesões</b>', 'Visceral: pulmonar, mucosa oral, gastrointestinal ou ganglionar', 'Disseminado: cutâneo + visceral')),
      C('sk-dx', 2024, 'Como se confirma o Sarcoma de Kaposi?',
        '<b>Biópsia</b> (padrão-ouro): angiogênese, inflamação e proliferação fusocelular, com imuno-histoquímica mostrando <b>HHV-8</b>. Principal diferencial cutâneo: <b>angiomatose bacilar</b>.'),
      C('sk-local', 2024, 'Sarcoma de Kaposi: quais as terapias locais e quando usar?',
        'Para lesões sintomáticas ou estigmatizantes (recaem e não evitam lesões novas): ' + ul('<b>Crioterapia</b> (nitrogênio líquido): 85% de resposta em 11 semanas', '<b>Quimioterapia intralesional</b> (vincristina, vimblastina): 74% de resposta; efeito adverso hiperpigmentação', '<b>Radioterapia</b> para poucas lesões em área limitada') + 'A maioria dos pacientes de baixo risco responde só à <b>TARV</b>.'),
      C('sk-sist', 2024, 'Quando indicar terapia sistêmica no Sarcoma de Kaposi e com quais drogas?',
        'Doença <b>disseminada, progressiva ou sintomática</b>: quimioterapia citotóxica (vimblastina, vincristina, bleomicina, doxorrubicina, doxorrubicina ou daunorrubicina lipossomal, paclitaxel).'),
      C('ab-agente', 2026, 'Qual o agente da angiomatose bacilar?', 'Bactérias do gênero <b>Bartonella</b> (B. henselae e B. quintana).'),
      C('ab-vs-sk', 2026, 'Angiomatose bacilar × Sarcoma de Kaposi: como diferenciar?',
        'Lesões muito parecidas (pápulas/nódulos friáveis "em framboesa" que sangram, como granuloma piogênico). A angiomatose: lesões <b>dolorosas</b>, mais acometimento <b>sistêmico</b> (febre, perda de peso), progressão mais rápida e <b>lesões ósseas osteolíticas dolorosas</b>.',
        '<b>Macete:</b> lesão vascular + osteólise dolorosa = Bartonella.'),
    ]),

    S('inf-bart', 'Linfadenopatia e doença da arranhadura do gato', [
      C('abord', 2023, 'Como começar a avaliação de uma linfadenopatia?',
        'Separar <b>localizada × generalizada</b>. Nas localizadas, o sítio (epitroclear, supraclavicular, axilar, inguinal, pré/retroauricular, cervical) orienta as causas mais prováveis.'),
      C('gato-def', 2023, 'Doença da arranhadura do gato: agente e manifestações?',
        '<b>Bartonella henselae</b> (bacilo gram-negativo), após mordida ou arranhadura de gato. Lesão cutânea + linfadenopatia, febre de origem indeterminada, acometimento visceral, <b>neurorretinite</b> e SNC.'),
      C('gato-dx', 2023, 'Como se diagnostica a doença da arranhadura do gato?', 'Combinação de sorologia, PCR, histopatologia e cultura do tecido.'),
      C('gato-tto', 2023, 'Qual o tratamento da doença da arranhadura do gato?',
        tb(['Forma', 'Tratamento'], ['Leve', 'Azitromicina 5 dias'], ['Visceral / FOI', 'Azitromicina + rifampicina 10–14 dias'], ['Neurorretinite / SNC', 'Rifampicina ou doxiciclina 4–6 semanas'])),
    ]),

    S('inf-sif', 'Sífilis', [
      C('resposta', 2023, 'Qual a queda de título esperada após o tratamento da sífilis?',
        'Queda de <b>2 diluições em até 3 meses</b> e <b>4 diluições em até 6 meses</b> no teste não treponêmico, até a sororreversão.'),
      C('resp-imuno', 2023, 'Como se define hoje a resposta imunológica adequada na sífilis adquirida?',
        'Teste não treponêmico <b>não reagente</b> ou queda de <b>2 diluições em até 6 meses</b> (sífilis recente) ou <b>12 meses</b> (sífilis tardia).'),
      C('retrat', 2023, 'Quais os critérios de retratamento da sífilis?',
        ul('Não cair <b>2 diluições</b> em 6 meses (recente) ou 12 meses (tardia) — ex.: de 1:32 para &gt; 1:8', 'Subir <b>2 ou mais diluições</b> — ex.: de 1:16 para 1:64', 'Sinais e sintomas persistentes ou recorrentes')),
      C('neuro', 2023, 'Quando investigar neurossífilis (punção lombar) no retratamento?',
        'População geral: quando <b>não houve exposição sexual</b> que justifique reinfecção. Pessoas com <b>HIV</b>: em <b>todos</b> os retratamentos, com ou sem nova exposição.'),
      C('maligna', 2024, 'Placas e nódulos dolorosos que ulceram, com crostas rupioides, em paciente com HIV avançado: qual a hipótese?',
        '<b>Sífilis maligna</b> (ulceronodular, lues maligna, sífilis rupioide): forma cutânea grave. Coinfecção com HIV aumenta o risco em <b>60 vezes</b>.'),
      C('maligna-hist', 2024, 'Qual a histologia da sífilis maligna?',
        'Infiltrado denso, <b>granulomatoso não caseoso</b>, com plasmócitos e histiócitos.'),
      C('secund', 2024, 'Quais manifestações raras da sífilis secundária foram citadas?',
        'Osteíte/periostite, artrite, glomerulonefrite, hepatite e síndrome nefrótica.'),
    ]),

    S('inf-tb', 'Tuberculose', [
      C('hiv', 2024, 'HIV com imunossupressão avançada: que forma de TB esperar e como fica o PPD?',
        'Maior risco de TB <b>extrapulmonar e disseminada</b>; o PPD é frequentemente <b>negativo</b>.'),
      C('iltb', 2026, 'Imunossuprimida, contactante próxima de bacilífero, RX normal e PPD/IGRA negativos: qual a conduta?',
        'RX normal e ausência de clínica afastam TB ativa → <b>tratar ILTB mesmo com PPD/IGRA negativos</b>.'),
    ]),

    S('inf-imuno', 'Infecções no imunossuprimido e no transplante', [
      C('tx-1m', 2025, 'Transplantado no primeiro mês: quais infecções predominam?',
        'Infecções preexistentes e <b>complicações pós-cirúrgicas</b>: pneumonia aspirativa, corrente sanguínea, trato urinário. Bactérias e fungos.'),
      C('tx-6m', 2025, 'Transplantado entre 1 e 6 meses: quais infecções predominam?',
        '<b>Oportunistas</b>: <b>P. jirovecii</b>, <b>CMV</b>, herpes e micobactérias não tuberculosas.'),
      C('tx-tarde', 2025, 'Transplantado após 6–12 meses: qual o padrão de infecção?',
        'Risco menor; infecções <b>comunitárias</b> (pneumonias virais, Legionella).'),
      C('les-lcr', 2024, 'Paciente com LES imunossuprimido, grave, com bastonetes gram-negativos no líquor: qual antibiótico e por que pensar em ivermectina?',
        '<b>Ceftriaxona</b> (cobre muitos bacilos gram-negativos; usada em meningite e pneumonia). <b>Ivermectina</b>: imunossuprimido tem risco de quadro parasitário grave (estrongiloidíase disseminada, que carreia gram-negativos).'),
      C('pl-tc', 2025, 'Imunossuprimido febril com déficit focal: pode puncionar direto?',
        'Não. A punção lombar só <b>após a TC de crânio</b>, pelo risco de <b>herniação</b> se houver lesão expansiva.'),
    ]),

    S('inf-grave', 'Infecções bacterianas graves', [
      C('strep', 2024, 'Síndrome do choque tóxico estreptocócico: mecanismo e tratamento?',
        '<b>Exotoxinas</b> do S. pyogenes → liberação maciça de citocinas → febre, hipotensão, choque. Tratamento: <b>penicilina cristalina + clindamicina</b>.'),
      C('menin-vs-fmb', 2024, 'Meningococcemia × febre maculosa: qual o tratamento de cada uma?',
        'Meningococcemia: <b>ceftriaxona 2 g 12/12 h</b>. Febre maculosa: <b>doxiciclina</b> (2ª opção: cloranfenicol).'),
      C('actino-clin', 2025, 'Actinomicose: como se apresenta e qual a forma mais comum?',
        'Abscessos, induração, trajetos sinusais drenando, fístulas e fibrose. A forma <b>cervicofacial</b> é a mais comum (50%).'),
      C('actino-chave', 2025, 'Quais duas características distinguem a actinomicose?',
        'Disseminação <b>através de planos teciduais</b> (não respeita barreiras anatômicas) e <b>grânulos de enxofre</b> amarelados no pus. Tratamento: <b>amoxicilina</b> é uma das opções.'),
    ]),

    S('inf-flu', 'Síndrome gripal e influenza', [
      C('sg', 2023, 'Como se define síndrome gripal?',
        'Febre + tosse ou dor de garganta + pelo menos um: cefaleia, mialgia ou artralgia.'),
      C('srag', 2023, 'Como se define SRAG?',
        'Síndrome gripal + gravidade: dispneia, desconforto respiratório, <b>saturação &lt; 95%</b> ou exacerbação de doença prévia.'),
      C('dx', 2023, 'Qual o padrão-ouro para o diagnóstico de influenza?', '<b>RT-PCR em tempo real.</b>'),
      C('tto', 2023, 'Oseltamivir: quando iniciar, por quanto tempo e para quem?',
        'Idealmente nas <b>primeiras 48 h</b>, por <b>5 dias</b>. Indicações principais: idosos ≥ 60 anos, crianças &lt; 5 anos, gestantes e puérperas, imunossuprimidos, algumas comorbidades e obesos.'),
    ]),

    S('inf-diar', 'Diarreias infecciosas e parasitoses intestinais', [
      C('tipos', 2022, 'Como se classificam as diarreias pela duração?',
        tb(['Tipo', 'Definição'], ['Aguda aquosa', 'Até 14 dias, grande perda de líquido; bactérias e vírus'], ['Aguda com sangue (disenteria)', 'Lesão de mucosa; <b>Shigella</b> é a principal causa'], ['Persistente', '<b>≥ 14 dias</b>; alto risco de complicações e letalidade'], ['Crônica', '<b>≥ 4 semanas</b>'])),
      C('exames', 2022, 'Diarreia aguda: quando pedir exames e quais?',
        '<b>Quando</b>: disenteria (sangue e muco), episódio moderado/grave, &gt; 7 dias, imunossuprimidos, &gt; 70 anos, muitas comorbidades. <b>Quais</b>: hemograma, função renal, eletrólitos e fezes (antígenos, cultura, parasitológico).'),
      C('parasitas', 2025, 'Que tipo de diarreia causam Cryptosporidium, Microsporidium e Giardia?',
        ul('<b>Cryptosporidium</b>: aquosa, sem muco ou sangue', '<b>Microsporidium</b>: aquosa crônica', '<b>Giardia</b>: crônica com <b>esteatorreia</b> e má absorção')),
      C('ameba-clin', 2025, 'Amebíase intestinal: clínica e fatores de risco?',
        '<b>Entamoeba histolytica</b>: diarreia <b>sanguinolenta</b>, dor abdominal e febre (de assintomática a colite fulminante). Risco: imunossupressão, corticoide, desnutrição, alcoolismo.'),
      C('ameba-dx', 2025, 'Amebíase: como diagnosticar e o que mostra a colonoscopia?',
        'Cistos ou trofozoítos nas fezes, antígeno fecal ou PCR. Colonoscopia: <b>úlceras rasas em forma de frasco</b>, principalmente no <b>ceco</b> e cólon.'),
    ]),
  ],
};
