const { C, S, ul, tb } = require('./_h');

module.exports = {
  id: 'reu', nome: 'Reumatologia', ic: '🦴',
  desc: 'LES e nefrite lúpica, AR, Still, espondiloartrites e Behçet, vasculites, crioglobulinemia, IgG4, Sjögren e esclerodermia.',
  subs: [
    S('reu-les', 'LES e nefrite lúpica', [
      C('nl-epi', 2026, 'Nefrite lúpica: quando costuma surgir e quem tem mais risco?',
        'Nos primeiros <b>6–36 meses</b> da doença. Mais frequente em <b>homens, negros, hispânicos e asiáticos</b>.'),
      C('nl-aval', 2026, 'Como se faz a avaliação inicial da nefrite lúpica (que pode ser assintomática)?',
        'Urina 1, função renal, proteinúria de 24 h, <b>complemento</b> e <b>anti-DNA</b>.'),
      C('nl-2exames', 2026, 'Quais os dois exames essenciais na investigação da nefrite lúpica?',
        '<b>Relação proteína/creatinina</b> em amostra isolada e <b>dismorfismo eritrocitário</b> (hematúria glomerular).'),
      C('nl-bx', 2026, 'Quais as indicações de biópsia renal no LES?',
        ul('Proteinúria <b>≥ 500 mg/dia</b> ou relação P/C <b>≥ 0,5</b>', 'Piora da função renal sem causa conhecida (creatinina <b>↑ 30%</b>)', 'Hematúria glomerular mesmo com proteinúria &lt; 500 mg/dia', 'Avaliação de diagnósticos diferenciais')),
      C('nl-classes', 2026, 'Nefrite lúpica: quais classes lembrar e onde ficam os depósitos?',
        '<b>Classe IV</b>: mais comum e mais grave. <b>Classe V</b>: membranosa. Depósitos <b>subendoteliais</b> → proliferativa (III ou IV); <b>subepiteliais</b> → membranosa (V).',
        '<b>Macete:</b> subENDOtelial = proliferativa; subEPItelial = membranosa.'),
      C('nl-tto', 2026, 'Como se organiza o tratamento da nefrite lúpica?', 'Em duas fases: <b>indução</b> e depois <b>manutenção</b>.'),
      C('nl-compl', [2024, 2025], 'Nefrite lúpica: como está o complemento e qual o padrão da imunofluorescência?',
        'Complemento <b>consumido</b>, com grandes depósitos de imunocomplexos. Imunofluorescência <b>granular</b>.'),
    ]),

    S('reu-ar', 'Artrite reumatoide, Felty e pulmão reumatoide', [
      C('def', 2026, 'Artrite reumatoide: epidemiologia e padrão articular?',
        'Artropatia inflamatória crônica mais comum, mulheres de meia-idade. <b>Poliartrite</b> de ritmo inflamatório em pequenas articulações de mãos, punhos e pés, <b>rigidez matinal &gt; 1 h</b>.'),
      C('morte', 2026, 'Quais as duas principais causas de morte na AR?',
        '1ª: <b>doença cardiovascular</b> (dobro do risco de IAM, até 50% mais mortalidade CV). 2ª: <b>manifestações pulmonares</b> (intersticial, derrame pleural, nódulos reumatoides, vias aéreas).'),
      C('mtx-pulmao', 2026, 'Metotrexato aumenta o risco de doença intersticial na AR?',
        'Não. O MTX <b>não</b> se associa a desenvolvimento ou progressão da intersticiopatia. A pneumonite idiossincrática por MTX existe, mas é <b>rara e aguda</b>, diferente da intersticiopatia crônica.'),
      C('dpi-conduta', 2026, 'AR em uso de MTX com dispneia progressiva, hipoxemia e TC de doença intersticial: qual a conduta que a banca considerou correta?',
        '<b>Suspender o metotrexato</b> (possível toxicidade ou piora da DPI) e iniciar <b>corticoide sistêmico</b>. Antifibróticos (pirfenidona) <b>não</b> são tratamento inicial: ficam para fibrose progressiva refratária.'),
      C('felty', 2025, 'Síndrome de Felty: qual a tríade?',
        '<b>AR de longa data + esplenomegalia + neutropenia.</b>',
        '<b>Macete:</b> AR + baço grande + neutropenia = Felty.'),
      C('felty-tto', 2025, 'Síndrome de Felty: qual o risco principal e o tratamento?',
        'A neutropenia aumenta o risco de <b>infecções graves</b>. Tratamento: <b>metotrexato e rituximabe</b>; <b>G-CSF</b> na neutropenia refratária; <b>esplenectomia</b> nos graves e resistentes.'),
    ]),

    S('reu-dsa', 'Doença de Still do adulto', [
      C('suspeita', [2024, 2025], 'Rash evanescente + febre vespertina: qual diagnóstico?',
        '<b>Doença de Still do adulto.</b> Doença inflamatória poligênica rara, predomínio feminino, 35–40 anos.'),
      C('clin', 2024, 'Quais as manifestações clínicas da doença de Still do adulto?',
        'Febre, erupção <b>rosa-salmão evanescente</b> que coincide com os picos febris, artrite/artralgia (punhos, joelhos, tornozelos), linfonodomegalia e hepatoesplenomegalia.'),
      C('lab', [2024, 2025], 'Quais os achados laboratoriais da doença de Still?',
        '<b>Leucocitose neutrofílica importante</b> (diferente das outras doenças reumatológicas, que dão linfopenia), <b>ferritina elevadíssima (&gt; 1.000 ng/mL)</b>, plaquetose, provas inflamatórias altas, anemia de doença crônica e complemento aumentado.'),
      C('yamaguchi', 2025, 'Quais os critérios de Yamaguchi?',
        '<b>Maiores</b>: febre ≥ 39 °C diária por ≥ 1 semana; artrite/artralgia ≥ 2 semanas; rash evanescente salmão; leucocitose ≥ 10.000 com neutrofilia. <b>Menores</b>: faringite; linfadenopatia e/ou esplenomegalia; transaminases altas; FR e FAN negativos. Diagnóstico com <b>5 critérios, sendo ≥ 2 maiores</b>.'),
      C('sam', 2025, 'Qual a principal complicação da doença de Still?',
        '<b>Síndrome de ativação macrofágica</b>: suspeitar diante de queda abrupta das células do sangue.'),
      C('tto', 2024, 'Qual o tratamento da doença de Still do adulto?',
        'Antes do diagnóstico: AINE. Confirmado: <b>corticoide</b> (1ª linha), com <b>metotrexato ou ciclosporina</b> se refratário. Casos mais graves: <b>anti-IL-6 (tocilizumabe)</b> ou <b>anti-IL-1 (anakinra, canaquinumabe)</b>.'),
    ]),

    S('reu-spa', 'Espondiloartrites, artrite reativa e Behçet', [
      C('ea', 2026, 'Lombalgia com início &lt; 40 anos, rigidez matinal prolongada, melhora com movimento, Schober positivo e HLA-B27: qual diagnóstico?',
        '<b>Espondilite anquilosante / espondiloartrite axial</b> (dor lombar inflamatória).'),
      C('reativa', 2025, 'Artrite reativa: quem acomete e qual o antecedente-chave?',
        'Adultos jovens (20–40 anos), sobretudo homens, com artrite assimétrica, uveíte e lesões de pele. Antecedente de infecção <b>gastrointestinal ou geniturinária</b> (Chlamydia trachomatis, Yersinia, Salmonella, Shigella, Campylobacter). <b>HLA-B27</b> em 50–80%.'),
      C('reativa-dica', 2025, 'Úlceras orais indolores + uveíte + ceratodermia blenorrágica: pense em quê?',
        '<b>Artrite reativa.</b> Tratamento: controle da dor e da inflamação.'),
      C('behcet-vs', 2025, 'Behçet × artrite reativa: o que diferencia?',
        'No Behçet as úlceras orais são <b>dolorosas</b>, a artrite é mais leve e não deformante, e a pele mostra <b>pústulas ou eritema nodoso</b> (não lesões vesicopustulares/ceratodermia).'),
      C('behcet-chave', 2024, 'Behçet: tem autoanticorpos? Acomete o rim? Qual úlcera é mais específica?',
        '<b>Sem autoanticorpos</b> e não costuma ter atividade renal. As úlceras <b>genitais</b> são as mais específicas.'),
      C('behcet-dd', 2025, 'Diferenciais do Behçet: o que distingue cada um?',
        tb(['Doença', 'Diferença'], ['Crohn', 'Diarreia e dor abdominal; úlceras genitais raras'], ['Sífilis', 'Úlcera genital da sífilis primária, não recorrente'], ['Linfogranuloma venéreo', 'Úlcera genital inicial + adenopatia inguinal dolorosa'], ['LES', 'Úlceras orais <b>indolores</b>, geralmente sem genitais'], ['Doença de Sweet', 'Pápulas e nódulos, sem úlceras orais/genitais'])),
    ]),

    S('reu-vasc', 'Vasculites: PAN, Takayasu e ANCA', [
      C('pan-def', 2023, 'Poliarterite nodosa: calibre, órgão poupado e causas secundárias?',
        'Vasculite necrosante de <b>médio calibre</b>; <b>poupa os pulmões</b>. Idiopática ou secundária, principalmente a <b>hepatite B</b>, hepatite C e HIV. Homens ~50 anos. Há formas de um órgão só (apêndice, vesícula, testículo) e a PAN cutânea.'),
      C('pan-clin', 2023, 'PAN: manifestações na pele, nervo, rim e outros órgãos?',
        ul('Pele: púrpura palpável, livedo, úlceras; biópsia com vasculite leucocitoclástica', 'Nervo: <b>mononeurite múltipla</b> (pé ou mão caída)', 'Rim: estenoses/microaneurismas → <b>hipertensão (SRAA)</b> e isquemia renal', 'Mesentérica (isquemia) e testicular (dor testicular)'),
        '<b>Armadilha:</b> a PAN não causa glomerulonefrite.'),
      C('pan-dx', 2023, 'Como se faz o diagnóstico da PAN?',
        'Clínica + provas inflamatórias + pesquisa de HBV/HCV/HIV + ENMG para o nervo + biópsia (inflamação necrosante de artérias de pequeno/médio calibre) ou angiografia mostrando <b>estenoses ou microaneurismas</b>.'),
      C('pan-tto', 2023, 'Qual o tratamento da PAN?',
        'Leve, idiopática, cutânea ou FFS 0: <b>corticoide isolado</b>. Grave: <b>pulso de corticoide + ciclofosfamida</b>.'),
      C('takayasu', 2023, 'Mulher jovem com sintomas sistêmicos, sopro de insuficiência aórtica, diferença de PA entre os braços e alargamento mediastinal vascular: diagnóstico e conduta?',
        '<b>Arterite de Takayasu.</b> Iniciar <b>prednisona 0,5–1 mg/kg/dia</b> + um <b>DMARD</b> (recidiva frequente, poupar corticoide).'),
      C('pulm-rim', 2025, 'Síndrome pulmão-rim (hemoptise + insuficiência renal) com biópsia pauci-imune: qual diagnóstico?',
        'Vasculite associada ao <b>ANCA</b>: <b>granulomatose com poliangeíte</b> ou <b>poliangeíte microscópica</b>.'),
      C('if', 2025, 'Imunofluorescência na glomerulonefrite: pauci-imune, linear e granular — o que cada padrão sugere?',
        tb(['Padrão', 'Doença'], ['Pauci-imune', 'Vasculites ANCA (GPA, PAM)'], ['Linear', 'Síndrome de Goodpasture'], ['Granular', 'LES (imunocomplexos)']),
        '<b>Macete:</b> Linear = Goodpasture; Granular = imunocomplexo; Pauci = ANCA.'),
    ]),

    S('reu-crio', 'Crioglobulinemia', [
      C('tipos', 2024, 'Quais os 3 tipos de crioglobulinemia, frequência e associação?',
        tb(['Tipo', 'Composição', 'Associação'], ['I (10%)', 'Ig <b>monoclonal</b> (IgG ou IgM)', 'Linfoproliferativas: MGUS, mieloma, Waldenström, LLC'], ['II (65%)', 'IgM monoclonal com atividade de <b>FR</b> + Ig policlonal', '<b>Hepatite C</b>; autoimunes (LES, Sjögren); linfoproliferativas; HBV, HIV'], ['III (25%)', 'IgG policlonal + IgM policlonal', 'Autoimunes; infecções (HCV)']) + 'Tipos II e III = crioglobulinemia <b>mista</b>.'),
      C('clin', 2024, 'Qual o quadro clínico da crioglobulinemia?',
        '<b>Tríade de Meltzer</b>: <b>púrpura palpável, artralgia e fraqueza</b>. Também glomerulonefrite <b>membranoproliferativa</b> (20–30%) e neuropatia periférica.'),
      C('lab', 2024, 'Crioglobulinemia tipo II: quais achados laboratoriais característicos?',
        '<b>Consumo isolado de C4</b> e <b>fator reumatoide positivo</b>. Tratamento conforme a doença de base e a gravidade.'),
    ]),

    S('reu-igg4', 'Doença relacionada ao IgG4', [
      C('epi', 2023, 'Doença relacionada ao IgG4: quem acomete e quando suspeitar?',
        'Rara, <b>homens de meia-idade</b>. Suspeitar em: pancreatite de causa desconhecida, colangite esclerosante, sialoadenite bilateral, <b>fibrose retroperitoneal</b>, pseudotumor orbitário, proptose, IgG4 sérica &gt; 5× o normal.'),
      C('fenotipos', 2023, 'Quais os 4 fenótipos da doença relacionada ao IgG4?',
        ul('Pancreato-hepato-biliar', 'Fibrose retroperitoneal e aortite', 'Limitada a cabeça e pescoço', 'Síndrome de <b>Mikulicz</b> (sialoadenite esclerosante)') + 'Comuns: massas/pseudotumores, linfadenomegalia e perda de peso.'),
      C('colangite', 2023, 'Colangite esclerosante por IgG4 × colangite esclerosante primária: como diferenciar?',
        'Na IgG4: <b>infiltrado de IgG4</b> na histologia, <b>IgG4 sérica alta</b> e <b>boa resposta ao corticoide</b> (a CEP não responde). Presente em &gt; 70% dos casos de pancreatite autoimune por IgG4.'),
      C('lab', 2024, 'Quais alterações laboratoriais na doença por IgG4?',
        'Eosinofilia e <b>IgE elevada</b> (&gt; 50%) — resposta Th2; VHS e PCR altos; hipergamaglobulinemia policlonal (até 80%); complemento baixo e FAN/FR positivos em ~1/3; plasmoblastos CD19+ CD27+ CD38+.'),
      C('histo', 2024, 'Quais os achados de biópsia na doença por IgG4?',
        ul('Infiltrado linfoplasmocitário com <b>&gt; 10 células IgG4+</b> por campo de grande aumento', 'Relação <b>IgG4/IgG &gt; 40%</b>', 'Fibrose em padrão <b>estoriforme</b>', '<b>Flebite obliterante</b>') + 'O diagnóstico combina clínica, sorologia e histologia; biopsiar sempre que possível.'),
      C('tto', 2024, 'Qual o tratamento da doença relacionada ao IgG4?',
        '<b>Corticoide</b> (metilprednisolona 0,5–1 mg/kg/dia), às vezes com micofenolato. Recaída é comum: <b>rituximabe</b>. Sem resposta: abatacepte ou tocilizumabe. Casos leves só com linfonodos: observação é opção.'),
    ]),

    S('reu-sjo', 'Síndrome de Sjögren', [
      C('def', 2024, 'Síndrome de Sjögren: o que é e quem acomete?',
        'Doença inflamatória crônica das glândulas <b>lacrimais e salivares</b> → síndrome sicca. Mulheres (9:1), pico entre <b>40 e 60 anos</b>.'),
      C('extra', 2024, 'Quais as manifestações extraglandulares do Sjögren?',
        'Poliartrite não erosiva, vasculite cutânea, pneumonite (caracteristicamente <b>LIP</b>), bronquiolite, polineuropatia, <b>nefrite intersticial com ATR tipo I (distal)</b>.'),
      C('linfoma', 2024, 'Qual o risco oncológico aumentado no Sjögren primário?', '<b>Linfoma.</b>'),
      C('dd', 2024, 'Quais diferenciais excluir antes de atribuir sintomas secos ao Sjögren?',
        'Medicamentos, tabagismo, radioterapia de cabeça e pescoço, <b>hepatite C</b>, aids, sarcoidose, amiloidose, doença enxerto-hospedeiro e <b>doença por IgG4</b>.'),
    ]),

    S('reu-es', 'Esclerose sistêmica: crise renal', [
      C('def', 2022, 'Crise renal esclerodérmica: em qual forma e com qual anticorpo?',
        'Mais comum na forma <b>difusa</b>; associada ao <b>anti-RNA polimerase III</b>.'),
      C('clin', 2022, 'Como se apresenta a crise renal esclerodérmica?',
        'Início abrupto de <b>hipertensão moderada a grave</b> + lesão renal aguda, sedimento geralmente normal; pode ter anemia hemolítica microangiopática e plaquetopenia.'),
      C('risco', 2022, 'Quais os fatores de risco para crise renal esclerodérmica?',
        'Pele com envolvimento difuso, <b>glicocorticoide ≥ 15 mg/dia</b> de prednisona e, talvez, ciclosporina.',
        '<b>Armadilha:</b> corticoide em dose alta na esclerodermia difusa pode precipitar a crise renal.'),
    ]),
  ],
};
